In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
project_path = "/content/drive/MyDrive/turkish_legal_rag"
processed_path = f"{project_path}/data/processed"
faiss_path = f"{project_path}/outputs/faiss"

In [3]:
!pip install sentence-transformers faiss-cpu rank-bm25 transformers accelerate bitsandbytes rouge-score

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Collecting rank-bm25
  Downloading rank_bm25-0.2.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.28.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 52.3 MB/s eta 0:00:00
Downloading rank_bm25-0.2.2-py3-none-any.whl (8.6 kB)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 12.8 MB/s eta 0:00:00
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=6af032a6a0a90281881ec2c67eb995276dfacfbcfa514ce059bcf4562a20869e
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rank-bm25, faiss-cpu, rouge-score, bitsandbytes
Successfully installed bitsandbytes-0.49.2 faiss-cpu-1.13.2 rank-bm25-0.2.2 rouge-score-0.1.2

In [4]:
import pandas as pd
import os

chunks_df = pd.read_csv(f"{processed_path}/retrieval_corpus.csv")
test_qa_df = pd.read_csv(f"{processed_path}/test_qa.csv")

print(chunks_df.shape)
print(test_qa_df.shape)

(3775, 5)
(1500, 2)

In [5]:
eval_df = test_qa_df.sample(20, random_state=42).reset_index(drop=True)
eval_df.head()

,question,answer
0,Anayasanın 101. Maddesiyle İlgili Tartışmalar ...,Cumhurbaşkanının seçilme şartlarının sınırları...
1,"Bir grup vatandaş, belirli bir etnik grubun di...","Anayasanın 10. Maddesi, herkesin kanun önünde ..."
2,"Bir grup akademisyen, yaşama hakkının sınırlan...","Evet, Anayasanın 17. Maddesi, herkesin yaşama ..."
3,Geçici madde 20 ne zaman eklendi?,20 mayıs 2016 tarihinde.
4,Videoda TCK 121 ihlali sabit değil mi?,Bu tür hususlar dosyalarında bilişimci bilirki...

In [6]:
import torch

print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

CUDA available: True
Tesla T4

In [7]:
from huggingface_hub import login

login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [8]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch

llm_model_name = "mistralai/Mistral-7B-Instruct-v0.2"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

tokenizer = AutoTokenizer.from_pretrained(llm_model_name)

model = AutoModelForCausalLM.from_pretrained(
    llm_model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

print("LLM loaded:", llm_model_name)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/596 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

LLM loaded: mistralai/Mistral-7B-Instruct-v0.2

In [9]:
def build_rag_prompt(question, retrieved_contexts):
    context_text = "\n\n".join([
        f"[Context {i+1}]\n{ctx}"
        for i, ctx in enumerate(retrieved_contexts)
    ])

    prompt = f"""
You are a Turkish legal question answering assistant.
Answer the question only using the provided legal context.
If the answer is not found in the context, say that the answer cannot be found in the given context.
Give a clear and concise answer in Turkish.

Legal Context:
{context_text}

Question:
{question}

Answer:
"""
    return prompt.strip()

In [10]:
def generate_answer(prompt, max_new_tokens=180):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            temperature=0.0,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    if "Answer:" in generated_text:
        generated_text = generated_text.split("Answer:")[-1].strip()

    return generated_text

In [11]:
import faiss
import numpy as np
import pandas as pd
import re
from sentence_transformers import SentenceTransformer
from rank_bm25 import BM25Okapi

In [12]:
chunks_df = pd.read_csv(f"{processed_path}/retrieval_corpus.csv")

embedding_model_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
embedding_model = SentenceTransformer(embedding_model_name)

index = faiss.read_index(f"{faiss_path}/baseline_faiss.index")

print("Chunks:", chunks_df.shape)
print("FAISS vectors:", index.ntotal)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Chunks: (3775, 5)
FAISS vectors: 3775

In [13]:
def simple_turkish_tokenize(text):
    text = str(text).lower()
    text = re.sub(r"[^a-zçğıöşü0-9\s]", " ", text)
    tokens = text.split()

    stopwords = {
        "ve", "veya", "ile", "de", "da", "bir", "bu", "şu", "o",
        "için", "gibi", "olarak", "olan", "kadar", "ise", "ancak",
        "çok", "daha", "en", "mi", "mı", "mu", "mü"
    }

    return [t for t in tokens if t not in stopwords and len(t) > 1]


tokenized_corpus = [
    simple_turkish_tokenize(text)
    for text in chunks_df["chunk_text"].astype(str).tolist()
]

bm25 = BM25Okapi(tokenized_corpus)

print("BM25 ready.")

BM25 ready.

In [14]:
def min_max_normalize(scores):
    scores = np.array(scores, dtype=np.float32)

    if scores.max() == scores.min():
        return np.zeros_like(scores)

    return (scores - scores.min()) / (scores.max() - scores.min())


def hybrid_retrieve_top_k(query, model, index, chunks_df, bm25, k=5, alpha=0.5):
    query_embedding = model.encode([query], convert_to_numpy=True).astype("float32")
    faiss.normalize_L2(query_embedding)

    dense_scores, dense_indices = index.search(query_embedding, len(chunks_df))

    dense_scores = dense_scores[0]
    dense_indices = dense_indices[0]

    dense_score_map = {
        int(idx): float(score)
        for idx, score in zip(dense_indices, dense_scores)
    }

    dense_all_scores = np.array([
        dense_score_map.get(i, 0.0)
        for i in range(len(chunks_df))
    ])

    tokenized_query = simple_turkish_tokenize(query)
    bm25_scores = np.array(bm25.get_scores(tokenized_query))

    dense_norm = min_max_normalize(dense_all_scores)
    bm25_norm = min_max_normalize(bm25_scores)

    final_scores = alpha * dense_norm + (1 - alpha) * bm25_norm

    top_indices = np.argsort(final_scores)[::-1][:k]

    results = []

    for rank, idx in enumerate(top_indices, start=1):
        results.append({
            "rank": rank,
            "chunk_id": chunks_df.iloc[idx]["chunk_id"],
            "source": chunks_df.iloc[idx]["source"],
            "score": float(final_scores[idx]),
            "dense_score": float(dense_norm[idx]),
            "bm25_score": float(bm25_norm[idx]),
            "chunk_text": chunks_df.iloc[idx]["chunk_text"]
        })

    return results

In [15]:
test_results = hybrid_retrieve_top_k(
    "Egemenlik kime aittir?",
    embedding_model,
    index,
    chunks_df,
    bm25,
    k=3,
    alpha=0.5
)

for r in test_results:
    print(r["rank"], r["chunk_id"], r["score"])
    print(r["chunk_text"][:300])
    print("-" * 80)

1 chunk_000269 0.9583597779273987
Madde 6 – Egemenlik, kayıtsız şartsız Milletindir. Türk Milleti, egemenliğini, Anayasanın koyduğu esaslara göre, yetkili organları eliyle kullanır.
--------------------------------------------------------------------------------
2 chunk_003519 0.898059606552124
DÖRDÜNCÜ KISIM
Millete ve Devlete Karşı Suçlar ve Son Hükümler ÜÇÜNCÜ BÖLÜM
Devletin Egemenlik Alametlerine ve Organlarının Saygınlığına Karşı Suçlar
--------------------------------------------------------------------------------
3 chunk_002321 0.804427444934845
Madde 960- Ortaklık genel kurulunda rehinli pay senetlerini temsil etmek yetkisi, rehin
alacaklısına değil, pay sahibine aittir.
II I. Yönetim ve ödeme
--------------------------------------------------------------------------------

In [16]:
sample_row = eval_df.iloc[0]

question = sample_row["question"]
expected_answer = sample_row["answer"]

retrieved = hybrid_retrieve_top_k(
    question,
    embedding_model,
    index,
    chunks_df,
    bm25,
    k=3,
    alpha=0.5
)

contexts = [item["chunk_text"] for item in retrieved]
prompt = build_rag_prompt(question, contexts)

generated_answer = generate_answer(prompt)

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(expected_answer)

print("\nGENERATED ANSWER:")
print(generated_answer)

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

QUESTION:
Anayasanın 101. Maddesiyle İlgili Tartışmalar Nelerdir?

EXPECTED ANSWER:
Cumhurbaşkanının seçilme şartlarının sınırları ve uygulanması üzerine tartışmalar olabilir.

GENERATED ANSWER:
Anayasanın 101. Madde'si, vakıflar hakkında söz eder. Bu madde, vakıfların yeterli mal ve haklarının vakfedilebilir olduğunu ve bunların anlaşılabilen her türlü geliri veya ekonomik değeri olan hakların vakfedilebilir olduğunu söyler. Anayasanın temel ilkelerine, hukuka, ahlâka, millî birliğe ve millî menfaatlara aykırı veya belli bir ırk ya da cemaat mensupl

In [17]:
results = hybrid_retrieve_top_k(
    question,
    embedding_model,
    index,
    chunks_df,
    bm25,
    k=5,
    alpha=0.5
)

for r in results:
    print("=" * 80)
    print(r["chunk_id"], r["score"])
    print(r["chunk_text"][:500])

================================================================================
chunk_002446 0.9372999668121338
Madde 101- Vakıflar, gerçek veya tüzel kişilerin yeterli mal ve hakları belirli ve sürekli
bir amaca özgülemeleriyle oluşan tüzel kişiliğe sahip mal topluluklarıdır.
Bir malvarlığının bütünü veya gerçekleşmiş ya da gerçekleşeceği anlaşılan her türlü geliri
veya ekonomik değeri olan haklar vakfedilebilir.
(İptal üçüncü fıkra: Anayasa Mahkemesi’nin 17/4/2008 tarihli ve E.: 2005/14, K.:
2008/92 sayılı Kararı ile.)
Cumhuriyetin Anayasa ile belirlenen niteliklerine ve Anayasanın temel ilkele
================================================================================
chunk_000355 0.9126801490783691
Madde 176 – Anayasanın dayandığı temel görüş ve ilkeleri belirten başlangıç kısmı, Anayasa metnine dahildir.
================================================================================
chunk_000210 0.8682551383972168
Madde 158 – Uyuşmazlık Mahkemesi adli ve idari yargı mercileri arasındaki görev ve hüküm uyuşmazlıklarını kesin olarak çözümlemeye yetkilidir. [101]
================================================================================
chunk_000362 0.8658927083015442
e) Anayasanın halkoylaması sonucu kabulünün ilanıyle birlikte yürürlüğe girecek hükümleri ve mevcut ve kurulacak kurum, kuruluş ve kurullar için yeniden kanun yapılması veya mevcut kanunlarda değişiklik yapılması gerekiyorsa bunlara ilişkin işlemler mevcut kanunların Anayasaya aykırı olmayan hükümleri veya doğrudan Anayasa hükümleri, Anayasanın 11 inci maddesi gereğince uygulanır.
================================================================================
chunk_000346 0.8620749711990356
YEDİNCİ KISIM SON HÜKÜMLER I. Anayasanın değiştirilmesi, seçimlere ve halkoylamasına katılma:

In [18]:
results = hybrid_retrieve_top_k(
    question,
    embedding_model,
    index,
    chunks_df,
    bm25,
    k=10,
    alpha=0.5
)

for r in results:
    print("=" * 80)
    print(r["rank"], r["chunk_id"], r["score"], r["source"])
    print(r["chunk_text"][:500])

================================================================================
1 chunk_002446 0.9372999668121338 Türk Medeni Kanunu
Madde 101- Vakıflar, gerçek veya tüzel kişilerin yeterli mal ve hakları belirli ve sürekli
bir amaca özgülemeleriyle oluşan tüzel kişiliğe sahip mal topluluklarıdır.
Bir malvarlığının bütünü veya gerçekleşmiş ya da gerçekleşeceği anlaşılan her türlü geliri
veya ekonomik değeri olan haklar vakfedilebilir.
(İptal üçüncü fıkra: Anayasa Mahkemesi’nin 17/4/2008 tarihli ve E.: 2005/14, K.:
2008/92 sayılı Kararı ile.)
Cumhuriyetin Anayasa ile belirlenen niteliklerine ve Anayasanın temel ilkele
================================================================================
2 chunk_000355 0.9126801490783691 Türkiye Cumhuriyeti Anayasası
Madde 176 – Anayasanın dayandığı temel görüş ve ilkeleri belirten başlangıç kısmı, Anayasa metnine dahildir.
================================================================================
3 chunk_000210 0.8682551383972168 Türkiye Cumhuriyeti Anayasası
Madde 158 – Uyuşmazlık Mahkemesi adli ve idari yargı mercileri arasındaki görev ve hüküm uyuşmazlıklarını kesin olarak çözümlemeye yetkilidir. [101]
================================================================================
4 chunk_000362 0.8658927083015442 Türkiye Cumhuriyeti Anayasası
e) Anayasanın halkoylaması sonucu kabulünün ilanıyle birlikte yürürlüğe girecek hükümleri ve mevcut ve kurulacak kurum, kuruluş ve kurullar için yeniden kanun yapılması veya mevcut kanunlarda değişiklik yapılması gerekiyorsa bunlara ilişkin işlemler mevcut kanunların Anayasaya aykırı olmayan hükümleri veya doğrudan Anayasa hükümleri, Anayasanın 11 inci maddesi gereğince uygulanır.
================================================================================
5 chunk_000346 0.8620749711990356 Türkiye Cumhuriyeti Anayasası
YEDİNCİ KISIM SON HÜKÜMLER I. Anayasanın değiştirilmesi, seçimlere ve halkoylamasına katılma:
================================================================================
6 chunk_000348 0.8427067995071411 Türkiye Cumhuriyeti Anayasası
Anayasanın değiştirilmesi hakkındaki tekliflerin görüşülmesi ve kabulü, bu maddedeki kayıtlar dışında, kanunların görüşülmesi ve kabulü hakkındaki hükümlere tabidir.
================================================================================
7 chunk_000356 0.798232913017273 Türkiye Cumhuriyeti Anayasası
Madde kenar başlıkları, sadece ilgili oldukları maddelerin konusunu ve maddeler arasındaki sıralama ve bağlantıyı gösterir. Bu başlıklar, Anayasa metninden sayılmaz. II I. Anayasanın yürürlüğe girmesi
================================================================================
8 chunk_000366 0.7970221042633057 Türkiye Cumhuriyeti Anayasası
Temel hak ve hürriyetler, özlerine dokunulmaksızın yalnızca Anayasanın ilgili maddelerinde belirtilen sebeplere bağlı olarak ve ancak kanunla sınırlanabilir. Bu sınırlamalar, Anayasanın sözüne ve ruhuna, demokratik toplum düzeninin ve lâik Cumhuriyetin gereklerine ve ölçülülük ilkesine aykırı olamaz. II I. Temel hak ve hürriyetlerin kötüye kullanılamaması
================================================================================
9 chunk_002415 0.7781945466995239 Türk Medeni Kanunu
Madde 1001- Kat mülkiyetine konu olan bağımsız bölümler, ayrıca tutulacak kat
mülkiyeti kütüğüne yazılır.
Özel kanun hükümleri saklı kalmak üzere, kütükte yapılacak işlemler hakkında tapu
42 2/7/2018 tarihli ve 700 sayılı KHK’nin 139 uncu maddesiyle, bu fıkralarda yer alan “tüzükle” ibaresi
“Cumhurbaşkanınca çıkarılan yönetmelikle” şeklinde değiştirilmiştir.
43 2/7/2018 tarihli ve 700 sayılı KHK’nin 139 uncu maddesiyle, bu fıkralarda yer alan “tüzükle” ibaresi
“Cumhurbaşkanınca çıkarı
================================================================================
10 chunk_000267 0.7708158493041992 Türkiye Cumhuriyeti Anayasası
Madde 4 – Anayasanın 1 inci maddesindeki Devletin şeklinin Cumhuriyet olduğu hakkındaki hüküm ile, 2 nci maddesindeki Cumhuriyetin nitelikleri ve 3 üncü maddesi hükümleri değiştirilemez ve değiştirilmesi teklif edilemez. V. Devletin temel amaç ve görevleri

In [19]:
def detect_source_filter(query):
    q = str(query).lower()

    if "anayasa" in q or "anayasanın" in q:
        return "Türkiye Cumhuriyeti Anayasası"

    return None

In [20]:
def hybrid_retrieve_top_k_filtered(query, model, index, chunks_df, bm25, k=5, alpha=0.5):
    source_filter = detect_source_filter(query)

    candidate_df = chunks_df.copy()

    if source_filter is not None:
        candidate_df = candidate_df[
            candidate_df["source"].astype(str).str.lower() == source_filter.lower()
        ].reset_index(drop=True)

    if len(candidate_df) == 0:
        candidate_df = chunks_df.copy()

    # Bu basit çözüm: filtreli corpus için temporary dense index kuruyoruz
    candidate_texts = candidate_df["chunk_text"].astype(str).tolist()

    candidate_embeddings = embedding_model.encode(
        candidate_texts,
        convert_to_numpy=True,
        show_progress_bar=False
    ).astype("float32")

    faiss.normalize_L2(candidate_embeddings)

    temp_index = faiss.IndexFlatIP(candidate_embeddings.shape[1])
    temp_index.add(candidate_embeddings)

    tokenized_candidate_corpus = [
        simple_turkish_tokenize(text)
        for text in candidate_texts
    ]

    temp_bm25 = BM25Okapi(tokenized_candidate_corpus)

    return hybrid_retrieve_top_k(
        query,
        model,
        temp_index,
        candidate_df,
        temp_bm25,
        k=k,
        alpha=alpha
    )

In [21]:
filtered_results = hybrid_retrieve_top_k_filtered(
    question,
    embedding_model,
    index,
    chunks_df,
    bm25,
    k=5,
    alpha=0.5
)

for r in filtered_results:
    print("=" * 80)
    print(r["rank"], r["chunk_id"], r["score"], r["source"])
    print(r["chunk_text"][:600])

================================================================================
1 chunk_000210 0.8626564741134644 Türkiye Cumhuriyeti Anayasası
Madde 158 – Uyuşmazlık Mahkemesi adli ve idari yargı mercileri arasındaki görev ve hüküm uyuşmazlıklarını kesin olarak çözümlemeye yetkilidir. [101]
================================================================================
2 chunk_000355 0.7758653163909912 Türkiye Cumhuriyeti Anayasası
Madde 176 – Anayasanın dayandığı temel görüş ve ilkeleri belirten başlangıç kısmı, Anayasa metnine dahildir.
================================================================================
3 chunk_000537 0.7254406213760376 Türkiye Cumhuriyeti Anayasası
Cumhurbaşkanlığı seçiminde birinci oylamada gerekli çoğunluğun sağlanamaması halinde 101 inci maddedeki usule göre ikinci oylama yapılır. D. Seçimlerin geriye bırakılması ve ara seçimler [34]
================================================================================
4 chunk_000362 0.7193549275398254 Türkiye Cumhuriyeti Anayasası
e) Anayasanın halkoylaması sonucu kabulünün ilanıyle birlikte yürürlüğe girecek hükümleri ve mevcut ve kurulacak kurum, kuruluş ve kurullar için yeniden kanun yapılması veya mevcut kanunlarda değişiklik yapılması gerekiyorsa bunlara ilişkin işlemler mevcut kanunların Anayasaya aykırı olmayan hükümleri veya doğrudan Anayasa hükümleri, Anayasanın 11 inci maddesi gereğince uygulanır.
================================================================================
5 chunk_000346 0.7186008095741272 Türkiye Cumhuriyeti Anayasası
YEDİNCİ KISIM SON HÜKÜMLER I. Anayasanın değiştirilmesi, seçimlere ve halkoylamasına katılma:

In [22]:
sample_questions = [
    "Egemenlik kime aittir?",
    "Türkiye Cumhuriyetinin yönetim şekli nedir?",
    "Cumhurbaşkanının görev süresi kaç yıldır?",
    "Bir kimse en fazla kaç defa Cumhurbaşkanı seçilebilir?"
]

for q in sample_questions:
    print("=" * 100)
    print("QUESTION:", q)

    results = hybrid_retrieve_top_k_filtered(
        q,
        embedding_model,
        index,
        chunks_df,
        bm25,
        k=5,
        alpha=0.5
    )

    for r in results[:3]:
        print(r["rank"], r["chunk_id"], r["score"], r["source"])
        print(r["chunk_text"][:500])
        print("-" * 80)

====================================================================================================
QUESTION: Egemenlik kime aittir?
1 chunk_000269 0.9583597183227539 Türkiye Cumhuriyeti Anayasası
Madde 6 – Egemenlik, kayıtsız şartsız Milletindir. Türk Milleti, egemenliğini, Anayasanın koyduğu esaslara göre, yetkili organları eliyle kullanır.
--------------------------------------------------------------------------------
2 chunk_003519 0.8980596661567688 Türk Ceza Kanunu
DÖRDÜNCÜ KISIM
Millete ve Devlete Karşı Suçlar ve Son Hükümler ÜÇÜNCÜ BÖLÜM
Devletin Egemenlik Alametlerine ve Organlarının Saygınlığına Karşı Suçlar
--------------------------------------------------------------------------------
3 chunk_002321 0.8044273853302002 Türk Medeni Kanunu
Madde 960- Ortaklık genel kurulunda rehinli pay senetlerini temsil etmek yetkisi, rehin
alacaklısına değil, pay sahibine aittir.
II I. Yönetim ve ödeme
--------------------------------------------------------------------------------
====================================================================================================
QUESTION: Türkiye Cumhuriyetinin yönetim şekli nedir?
1 chunk_000000 0.9103504419326782 Türkiye Cumhuriyeti Anayasası
Türk Vatanı ve Milletinin ebedi varlığını ve Yüce Türk Devletinin bölünmez bütünlüğünü belirleyen bu Anayasa, Türkiye Cumhuriyetinin kurucusu, ölümsüz önder ve eşsiz kahraman Atatürk’ün belirlediği milliyetçilik anlayışı ve onun inkılap ve ilkeleri doğrultusunda;
--------------------------------------------------------------------------------
2 chunk_000001 0.8839095234870911 Türkiye Cumhuriyeti Anayasası
Dünya milletleri ailesinin eşit haklara sahip şerefli bir üyesi olarak, Türkiye Cumhuriyetinin ebedi varlığı, refahı, maddi ve manevi mutluluğu ile çağdaş medeniyet düzeyine ulaşma azmi yönünde;
--------------------------------------------------------------------------------
3 chunk_000054 0.8718113899230957 Türkiye Cumhuriyeti Anayasası
Yabancı devletlere Türkiye Cumhuriyetinin temsilcilerini gönderir, Türkiye Cumhuriyetine gönderilecek yabancı devlet temsilcilerini kabul eder. Milletlerarası andlaşmaları onaylar ve yayımlar. Anayasa değişikliklerine ilişkin kanunları gerekli gördüğü takdirde halkoyuna sunar. Milli güvenlik politikalarını belirler ve gerekli tedbirleri alır. Türkiye Büyük Millet Meclisi adına Türk Silahlı Kuvvetlerinin Başkomutanlığını temsil eder. Türk Silahlı Kuvvetlerinin kullanılmasına karar verir. Sürekli
--------------------------------------------------------------------------------
====================================================================================================
QUESTION: Cumhurbaşkanının görev süresi kaç yıldır?
1 chunk_000043 1.0 Türkiye Cumhuriyeti Anayasası
Cumhurbaşkanı, kırk yaşını doldurmuş, yükseköğrenim yapmış, milletvekili seçilme yeterliliğine sahip Türk vatandaşları arasından, doğrudan halk tarafından seçilir. Cumhurbaşkanının görev süresi beş yıldır. Bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir.
--------------------------------------------------------------------------------
2 chunk_000086 0.9484720230102539 Türkiye Cumhuriyeti Anayasası
Seçimlerinin birlikte yenilenmesine karar verilen Meclisin ve Cumhurbaşkanının yetki ve görevleri, yeni Meclisin ve Cumhurbaşkanının göreve başlamasına kadar devam eder. Bu şekilde seçilen Meclis ve Cumhurbaşkanının görev süreleri de beş yıldır. İ. Milli Savunma 1. Başkomutanlık ve Genelkurmay Başkanlığı
--------------------------------------------------------------------------------
3 chunk_000588 0.7688313722610474 Bilgi Edinme Kanunu
Kurul üyelerinin görev süreleri dört yıldır. Görev süresi sona erenler yeniden seçilebilirler. Görev süresi dolmadan görevinden ayrılan üyenin yerine aynı usule göre seçilen üye, yerine seçildiği üyenin görev süresini tamamlar. Yeni seçilen Kurul göreve başlayıncaya kadar önceki Kurul görevine devam eder.
--------------------------------------------------------------------------------
====================================================================================================
QUESTION: Bir kimse en fazla kaç defa Cumhurbaşkanı seçilebilir?
1 chunk_000043 1.0 Türkiye Cumhuriyeti Anayasası
Cumhurbaşkanı, kırk yaşını doldurmuş, yükseköğrenim yapmış, milletvekili seçilme yeterliliğine sahip Türk vatandaşları arasından, doğrudan halk tarafından seçilir. Cumhurbaşkanının görev süresi beş yıldır. Bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir.
--------------------------------------------------------------------------------
2 chunk_000085 0.7173948287963867 Türkiye Cumhuriyeti Anayasası
Cumhurbaşkanının ikinci döneminde Meclis tarafından seçimlerin yenilenmesine karar verilmesi halinde, Cumhurbaşkanı bir defa daha aday olabilir.
--------------------------------------------------------------------------------
3 chunk_000063 0.6716797351837158 Türkiye Cumhuriyeti Anayasası
Madde 106 – (Değişik: 21/1/2017-6771/10 md.) Cumhurbaşkanı, seçildikten sonra bir veya daha fazla Cumhurbaşkanı yardımcısı atayabilir.
--------------------------------------------------------------------------------

In [23]:
for q in sample_questions:
    print("=" * 100)
    print("QUESTION:", q)

    results = hybrid_retrieve_top_k_filtered(
        q,
        embedding_model,
        index,
        chunks_df,
        bm25,
        k=5,
        alpha=0.5
    )

    contexts = [r["chunk_text"] for r in results[:3]]

    prompt = build_rag_prompt(q, contexts)

    answer = generate_answer(prompt)

    print("\nGENERATED ANSWER:")
    print(answer)

====================================================================================================
QUESTION: Egemenlik kime aittir?

GENERATED ANSWER:
Egemenlik, Türk Milleti tarafından Anayasanın koyduğu esaslara göre, yetkili organları eliyle kullanılır (Context 1).

Therefore, the answer to the question is: "Egemenlik, Türk Milleti'ne aitdir." (Egemenlik belongs to the Turkish Nation.)
====================================================================================================
QUESTION: Türkiye Cumhuriyetinin yönetim şekli nedir?

GENERATED ANSWER:
Türkiye Cumhuriyetinin yönetim şekli, Cumhuriyet Sistemi (Cumhuriyet Cumhuriyetidir, önemli olarak Atatürk'un milliyetçilik anlayışına dayalı bir yönetim şekli olduğunu belirten Anayasasının kısaca, Türkiye Cumhuriyetinin ebedi varlığını ve Yüce Türk Devletinin bölünmez bütünlüğünü belirleyen bir anayasadır. Bu anayasanın kısaca, Türki
====================================================================================================
QUESTION: Cumhurbaşkanının görev süresi kaç yıldır?

GENERATED ANSWER:
Cumhurbaşkanının görev süresi beş yıldır. (Context 1)
====================================================================================================
QUESTION: Bir kimse en fazla kaç defa Cumhurbaşkanı seçilebilir?

GENERATED ANSWER:
En fazla üç defa Cumhurbaşkanı seçilebilir. Context 1'de belirtilen kurallara göre, bir kişi en fazla iki defa Cumhurbaşkanı seçilebilir. Context 2'de belirtilen durumda, Cumhurbaşkanın ikinci dönemde Meclis tarafından seçilmesi halinde, Cumhurbaşkanı bir defa daha aday olabilir. Bu durumda toplamda üç defa Cumhurbaşkanı olabilir. Context 3'te belirtilen yönetmelikle, Cumhurbaşkanın bir

In [24]:
base_eval_questions = [
    {
        "question": "Egemenlik kime aittir?",
        "expected_answer": "Egemenlik kayıtsız şartsız Milletindir."
    },
    {
        "question": "Türkiye Cumhuriyetinin yönetim şekli nedir?",
        "expected_answer": "Türkiye Devleti bir Cumhuriyettir."
    },
    {
        "question": "Cumhurbaşkanının görev süresi kaç yıldır?",
        "expected_answer": "Cumhurbaşkanının görev süresi beş yıldır."
    },
    {
        "question": "Bir kimse en fazla kaç defa Cumhurbaşkanı seçilebilir?",
        "expected_answer": "Bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir."
    }
]

base_eval_df = pd.DataFrame(base_eval_questions)
base_eval_df

,question,expected_answer
0,Egemenlik kime aittir?,Egemenlik kayıtsız şartsız Milletindir.
1,Türkiye Cumhuriyetinin yönetim şekli nedir?,Türkiye Devleti bir Cumhuriyettir.
2,Cumhurbaşkanının görev süresi kaç yıldır?,Cumhurbaşkanının görev süresi beş yıldır.
3,Bir kimse en fazla kaç defa Cumhurbaşkanı seçi...,Bir kimse en fazla iki defa Cumhurbaşkanı seçi...

In [25]:
base_results = []

for _, row in base_eval_df.iterrows():
    question = row["question"]
    expected_answer = row["expected_answer"]

    retrieved = hybrid_retrieve_top_k_filtered(
        question,
        embedding_model,
        index,
        chunks_df,
        bm25,
        k=5,
        alpha=0.5
    )

    contexts = [r["chunk_text"] for r in retrieved[:3]]
    prompt = build_rag_prompt(question, contexts)
    generated_answer = generate_answer(prompt)

    base_results.append({
        "question": question,
        "expected_answer": expected_answer,
        "generated_answer": generated_answer,
        "top1_chunk_id": retrieved[0]["chunk_id"],
        "top1_context": retrieved[0]["chunk_text"]
    })

base_rag_results_df = pd.DataFrame(base_results)
base_rag_results_df

,question,expected_answer,generated_answer,top1_chunk_id,top1_context
0,Egemenlik kime aittir?,Egemenlik kayıtsız şartsız Milletindir.,"Egemenlik, Türk Milleti tarafından Anayasanın ...",chunk_000269,"Madde 6 – Egemenlik, kayıtsız şartsız Milletin..."
1,Türkiye Cumhuriyetinin yönetim şekli nedir?,Türkiye Devleti bir Cumhuriyettir.,"Türkiye Cumhuriyetinin yönetim şekli, Cumhuriy...",chunk_000000,Türk Vatanı ve Milletinin ebedi varlığını ve Y...
2,Cumhurbaşkanının görev süresi kaç yıldır?,Cumhurbaşkanının görev süresi beş yıldır.,Cumhurbaşkanının görev süresi beş yıldır. (Con...,chunk_000043,"Cumhurbaşkanı, kırk yaşını doldurmuş, yükseköğ..."
3,Bir kimse en fazla kaç defa Cumhurbaşkanı seçi...,Bir kimse en fazla iki defa Cumhurbaşkanı seçi...,En fazla üç defa Cumhurbaşkanı seçilebilir. Co...,chunk_000043,"Cumhurbaşkanı, kırk yaşını doldurmuş, yükseköğ..."

In [26]:
for i, row in base_rag_results_df.iterrows():
    print("=" * 100)
    print("Index:", i)
    print("QUESTION:")
    print(row["question"])
    print("\nEXPECTED:")
    print(row["expected_answer"])
    print("\nGENERATED:")
    print(row["generated_answer"])

====================================================================================================
Index: 0
QUESTION:
Egemenlik kime aittir?

EXPECTED:
Egemenlik kayıtsız şartsız Milletindir.

GENERATED:
Egemenlik, Türk Milleti tarafından Anayasanın koyduğu esaslara göre, yetkili organları eliyle kullanılır (Context 1).

Therefore, the answer to the question is: "Egemenlik, Türk Milleti'ne aitdir." (Egemenlik belongs to the Turkish Nation.)
====================================================================================================
Index: 1
QUESTION:
Türkiye Cumhuriyetinin yönetim şekli nedir?

EXPECTED:
Türkiye Devleti bir Cumhuriyettir.

GENERATED:
Türkiye Cumhuriyetinin yönetim şekli, Cumhuriyet Sistemi (Cumhuriyet Cumhuriyetidir, önemli olarak Atatürk'un milliyetçilik anlayışına dayalı bir yönetim şekli olduğunu belirten Anayasasının kısaca, Türkiye Cumhuriyetinin ebedi varlığını ve Yüce Türk Devletinin bölünmez bütünlüğünü belirleyen bir anayasadır. Bu anayasanın kısaca, Türki
====================================================================================================
Index: 2
QUESTION:
Cumhurbaşkanının görev süresi kaç yıldır?

EXPECTED:
Cumhurbaşkanının görev süresi beş yıldır.

GENERATED:
Cumhurbaşkanının görev süresi beş yıldır. (Context 1)
====================================================================================================
Index: 3
QUESTION:
Bir kimse en fazla kaç defa Cumhurbaşkanı seçilebilir?

EXPECTED:
Bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir.

GENERATED:
En fazla üç defa Cumhurbaşkanı seçilebilir. Context 1'de belirtilen kurallara göre, bir kişi en fazla iki defa Cumhurbaşkanı seçilebilir. Context 2'de belirtilen durumda, Cumhurbaşkanın ikinci dönemde Meclis tarafından seçilmesi halinde, Cumhurbaşkanı bir defa daha aday olabilir. Bu durumda toplamda üç defa Cumhurbaşkanı olabilir. Context 3'te belirtilen yönetmelikle, Cumhurbaşkanın bir

In [27]:
manual_scores = [1.0, 0.5, 1.0, 0.0]

base_rag_results_df["manual_score"] = manual_scores

base_score = base_rag_results_df["manual_score"].mean()

print("Base RAG Manual Accuracy:", base_score)
base_rag_results_df

Base RAG Manual Accuracy: 0.625

,question,expected_answer,generated_answer,top1_chunk_id,top1_context,manual_score
0,Egemenlik kime aittir?,Egemenlik kayıtsız şartsız Milletindir.,"Egemenlik, Türk Milleti tarafından Anayasanın ...",chunk_000269,"Madde 6 – Egemenlik, kayıtsız şartsız Milletin...",1.0
1,Türkiye Cumhuriyetinin yönetim şekli nedir?,Türkiye Devleti bir Cumhuriyettir.,"Türkiye Cumhuriyetinin yönetim şekli, Cumhuriy...",chunk_000000,Türk Vatanı ve Milletinin ebedi varlığını ve Y...,0.5
2,Cumhurbaşkanının görev süresi kaç yıldır?,Cumhurbaşkanının görev süresi beş yıldır.,Cumhurbaşkanının görev süresi beş yıldır. (Con...,chunk_000043,"Cumhurbaşkanı, kırk yaşını doldurmuş, yükseköğ...",1.0
3,Bir kimse en fazla kaç defa Cumhurbaşkanı seçi...,Bir kimse en fazla iki defa Cumhurbaşkanı seçi...,En fazla üç defa Cumhurbaşkanı seçilebilir. Co...,chunk_000043,"Cumhurbaşkanı, kırk yaşını doldurmuş, yükseköğ...",0.0

In [28]:
base_rag_results_df.to_csv(
    f"{project_path}/outputs/metrics/base_rag_generation_results.csv",
    index=False,
    encoding="utf-8-sig"
)

pd.DataFrame([{
    "method": "Base RAG - Hybrid Retrieval + Base LLM",
    "manual_accuracy": base_score
}]).to_csv(
    f"{project_path}/outputs/metrics/base_rag_manual_score.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Base RAG results saved.")

Base RAG results saved.

## Experiment 2: Prompt-Improved RAG

In [29]:
def build_strict_rag_prompt(question, retrieved_contexts):
    context_text = "\n\n".join([
        f"[Context {i+1}]\n{ctx}"
        for i, ctx in enumerate(retrieved_contexts)
    ])

    prompt = f"""
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
{context_text}

Soru:
{question}

Kısa cevap:
"""
    return prompt.strip()

In [30]:
improved_results = []

for _, row in base_eval_df.iterrows():
    question = row["question"]
    expected_answer = row["expected_answer"]

    retrieved = hybrid_retrieve_top_k_filtered(
        question,
        embedding_model,
        index,
        chunks_df,
        bm25,
        k=5,
        alpha=0.5
    )

    contexts = [r["chunk_text"] for r in retrieved[:3]]

    prompt = build_strict_rag_prompt(question, contexts)

    generated_answer = generate_answer(prompt)

    improved_results.append({
        "question": question,
        "expected_answer": expected_answer,
        "generated_answer": generated_answer
    })

improved_rag_results_df = pd.DataFrame(improved_results)
improved_rag_results_df

,question,expected_answer,generated_answer
0,Egemenlik kime aittir?,Egemenlik kayıtsız şartsız Milletindir.,Sen Türk hukuk metinleri için çalışan dikkatli...
1,Türkiye Cumhuriyetinin yönetim şekli nedir?,Türkiye Devleti bir Cumhuriyettir.,Sen Türk hukuk metinleri için çalışan dikkatli...
2,Cumhurbaşkanının görev süresi kaç yıldır?,Cumhurbaşkanının görev süresi beş yıldır.,Sen Türk hukuk metinleri için çalışan dikkatli...
3,Bir kimse en fazla kaç defa Cumhurbaşkanı seçi...,Bir kimse en fazla iki defa Cumhurbaşkanı seçi...,Sen Türk hukuk metinleri için çalışan dikkatli...

In [31]:
for i, row in improved_rag_results_df.iterrows():
    print("=" * 100)
    print("QUESTION:")
    print(row["question"])
    print("\nEXPECTED:")
    print(row["expected_answer"])
    print("\nGENERATED:")
    print(row["generated_answer"])

====================================================================================================
QUESTION:
Egemenlik kime aittir?

EXPECTED:
Egemenlik kayıtsız şartsız Milletindir.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 6 – Egemenlik, kayıtsız şartsız Milletindir. Türk Milleti, egemenliğini, Anayasanın koyduğu esaslara göre, yetkili organları eliyle kullanır.

[Context 2]
DÖRDÜNCÜ KISIM
Millete ve Devlete Karşı Suçlar ve Son Hükümler ÜÇÜNCÜ BÖLÜM
Devletin Egemenlik Alametlerine ve Organlarının Saygınlığına Karşı Suçlar

[Context 3]
Madde 960- Ortaklık genel kurulunda rehinli pay senetlerini temsil etmek yetkisi, rehin
alacaklısına değil, pay sahibine aittir.
II I. Yönetim ve ödeme

Soru:
Egemenlik kime aittir?

Kısa cevap:
Egemenlik Türk Milleti'ne aittir.
====================================================================================================
QUESTION:
Türkiye Cumhuriyetinin yönetim şekli nedir?

EXPECTED:
Türkiye Devleti bir Cumhuriyettir.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Türk Vatanı ve Milletinin ebedi varlığını ve Yüce Türk Devletinin bölünmez bütünlüğünü belirleyen bu Anayasa, Türkiye Cumhuriyetinin kurucusu, ölümsüz önder ve eşsiz kahraman Atatürk’ün belirlediği milliyetçilik anlayışı ve onun inkılap ve ilkeleri doğrultusunda;

[Context 2]
Dünya milletleri ailesinin eşit haklara sahip şerefli bir üyesi olarak, Türkiye Cumhuriyetinin ebedi varlığı, refahı, maddi ve manevi mutluluğu ile çağdaş medeniyet düzeyine ulaşma azmi yönünde;

[Context 3]
Yabancı devletlere Türkiye Cumhuriyetinin temsilcilerini gönderir, Türkiye Cumhuriyetine gönderilecek yabancı devlet temsilcilerini kabul eder. Milletlerarası andlaşmaları onaylar ve yayımlar. Anayasa değişikliklerine ilişkin kanunları gerekli gördüğü takdirde halkoyuna sunar. Milli güvenlik politikalarını belirler ve gerekli tedbirleri alır. Türkiye Büyük Millet Meclisi adına Türk Silahlı Kuvvetlerinin Başkomutanlığını temsil eder. Türk Silahlı Kuvvetlerinin kullanılmasına karar verir. Sürekli hastalık, sakatlık ve kocama sebebiyle kişilerin cezalarını hafifletir veya kaldırır.

Soru:
Türkiye Cumhuriyetinin yönetim şekli nedir?

Kısa cevap:
Türkiye Cumhuriyetinin yönetim şekli, Cumhuriyet Sistemi (Cumhuriyet Başkanı, Milli Güvenlik Bakanı, Anayasa Mahkemesi vb.) ve Türk Silahlı Kuvvetlerinin Başkomutanlığı tarafından gerçekleştirilan bir çıkıştırılmış demokrasi ile ifade edilir.
====================================================================================================
QUESTION:
Cumhurbaşkanının görev süresi kaç yıldır?

EXPECTED:
Cumhurbaşkanının görev süresi beş yıldır.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Cumhurbaşkanı, kırk yaşını doldurmuş, yükseköğrenim yapmış, milletvekili seçilme yeterliliğine sahip Türk vatandaşları arasından, doğrudan halk tarafından seçilir. Cumhurbaşkanının görev süresi beş yıldır. Bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir.

[Context 2]
Seçimlerinin birlikte yenilenmesine karar verilen Meclisin ve Cumhurbaşkanının yetki ve görevleri, yeni Meclisin ve Cumhurbaşkanının göreve başlamasına kadar devam eder. Bu şekilde seçilen Meclis ve Cumhurbaşkanının görev süreleri de beş yıldır. İ. Milli Savunma 1. Başkomutanlık ve Genelkurmay Başkanlığı

[Context 3]
Kurul üyelerinin görev süreleri dört yıldır. Görev süresi sona erenler yeniden seçilebilirler. Görev süresi dolmadan görevinden ayrılan üyenin yerine aynı usule göre seçilen üye, yerine seçildiği üyenin görev süresini tamamlar. Yeni seçilen Kurul göreve başlayıncaya kadar önceki Kurul görevine devam eder.

Soru:
Cumhurbaşkanının görev süresi kaç yıldır?

Kısa cevap:
Cumhurbaşkanının görev süresi beş yıldır.
====================================================================================================
QUESTION:
Bir kimse en fazla kaç defa Cumhurbaşkanı seçilebilir?

EXPECTED:
Bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Cumhurbaşkanı, kırk yaşını doldurmuş, yükseköğrenim yapmış, milletvekili seçilme yeterliliğine sahip Türk vatandaşları arasından, doğrudan halk tarafından seçilir. Cumhurbaşkanının görev süresi beş yıldır. Bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir.

[Context 2]
Cumhurbaşkanının ikinci döneminde Meclis tarafından seçimlerin yenilenmesine karar verilmesi halinde, Cumhurbaşkanı bir defa daha aday olabilir.

[Context 3]
Madde 106 – (Değişik: 21/1/2017-6771/10 md.) Cumhurbaşkanı, seçildikten sonra bir veya daha fazla Cumhurbaşkanı yardımcısı atayabilir.

Soru:
Bir kimse en fazla kaç defa Cumhurbaşkanı seçilebilir?

Kısa cevap:
Bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir. (Context 1)

Detaylı cevap:
Cumhurbaşkanın seçilme sürecinde, Türk vatandaşları arasından doğrudan halk tarafından seçilir. Bir kimse en fazla iki defa Cumhurbaşkanı seçilebilir. (Context 1)

Bazen, Cumhurbaşkanın ikinci döneminde Meclis tarafından seçimlerin yenilenmesine karar verilmesi halinde, Cumhurbaşkanı bir

In [32]:
manual_scores_improved = [1.0, 0.0, 1.0, 1.0]

improved_rag_results_df["manual_score"] = manual_scores_improved

improved_score = improved_rag_results_df["manual_score"].mean()

print("Improved Prompt RAG Accuracy:", improved_score)
improved_rag_results_df

Improved Prompt RAG Accuracy: 0.75

,question,expected_answer,generated_answer,manual_score
0,Egemenlik kime aittir?,Egemenlik kayıtsız şartsız Milletindir.,Sen Türk hukuk metinleri için çalışan dikkatli...,1.0
1,Türkiye Cumhuriyetinin yönetim şekli nedir?,Türkiye Devleti bir Cumhuriyettir.,Sen Türk hukuk metinleri için çalışan dikkatli...,0.0
2,Cumhurbaşkanının görev süresi kaç yıldır?,Cumhurbaşkanının görev süresi beş yıldır.,Sen Türk hukuk metinleri için çalışan dikkatli...,1.0
3,Bir kimse en fazla kaç defa Cumhurbaşkanı seçi...,Bir kimse en fazla iki defa Cumhurbaşkanı seçi...,Sen Türk hukuk metinleri için çalışan dikkatli...,1.0

In [33]:
def clean_generated_answer(text):
    if "Kısa cevap:" in text:
        text = text.split("Kısa cevap:")[-1].strip()

    if "Detaylı cevap:" in text:
        text = text.split("Detaylı cevap:")[0].strip()

    return text.strip()

In [34]:
improved_rag_results_df.to_csv(
    f"{project_path}/outputs/metrics/prompt_improved_rag_generation_results.csv",
    index=False,
    encoding="utf-8-sig"
)

pd.DataFrame([{
    "method": "Prompt Improved RAG - Hybrid Retrieval + Base LLM",
    "manual_accuracy": improved_score
}]).to_csv(
    f"{project_path}/outputs/metrics/prompt_improved_rag_manual_score.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Prompt improved RAG results saved.")

Prompt improved RAG results saved.

In [35]:
rag_comparison_df = pd.DataFrame([
    {
        "method": "Base RAG",
        "manual_accuracy": base_score
    },
    {
        "method": "Prompt Improved RAG",
        "manual_accuracy": improved_score
    }
])

rag_comparison_df

                method  manual_accuracy
0             Base RAG            0.625
1  Prompt Improved RAG            0.750

## Test Set Evaluation

In [36]:
test_qa_df = pd.read_csv(f"{project_path}/data/processed/test_qa.csv")

test_eval_df = test_qa_df.sample(n=20, random_state=42).reset_index(drop=True)

print(test_eval_df.shape)
test_eval_df.head()

(20, 2)

,question,answer
0,Anayasanın 101. Maddesiyle İlgili Tartışmalar ...,Cumhurbaşkanının seçilme şartlarının sınırları...
1,"Bir grup vatandaş, belirli bir etnik grubun di...","Anayasanın 10. Maddesi, herkesin kanun önünde ..."
2,"Bir grup akademisyen, yaşama hakkının sınırlan...","Evet, Anayasanın 17. Maddesi, herkesin yaşama ..."
3,Geçici madde 20 ne zaman eklendi?,20 mayıs 2016 tarihinde.
4,Videoda TCK 121 ihlali sabit değil mi?,Bu tür hususlar dosyalarında bilişimci bilirki...

In [37]:
base_test_results = []

for _, row in test_eval_df.iterrows():
    question = row["question"]
    expected_answer = row["answer"]

    retrieved = hybrid_retrieve_top_k_filtered(
        question,
        embedding_model,
        index,
        chunks_df,
        bm25,
        k=5,
        alpha=0.5
    )

    contexts = [r["chunk_text"] for r in retrieved[:3]]
    prompt = build_rag_prompt(question, contexts)
    generated_answer = generate_answer(prompt)

    base_test_results.append({
        "question": question,
        "expected_answer": expected_answer,
        "generated_answer": generated_answer,
        "top1_chunk_id": retrieved[0]["chunk_id"],
        "top1_context": retrieved[0]["chunk_text"]
    })

base_test_results_df = pd.DataFrame(base_test_results)
base_test_results_df.head()

,question,expected_answer,generated_answer,top1_chunk_id,top1_context
0,Anayasanın 101. Maddesiyle İlgili Tartışmalar ...,Cumhurbaşkanının seçilme şartlarının sınırları...,"Anayasanın 101. Madde'si, Uyuşmazlık Mahkemesi...",chunk_000210,Madde 158 – Uyuşmazlık Mahkemesi adli ve idari...
1,"Bir grup vatandaş, belirli bir etnik grubun di...","Anayasanın 10. Maddesi, herkesin kanun önünde ...",Bu durum Anayasanın 150. Madde ile ilgili olab...,chunk_000188,"Madde 150 – Kanunların, Cumhurbaşkanlığı karar..."
2,"Bir grup akademisyen, yaşama hakkının sınırlan...","Evet, Anayasanın 17. Maddesi, herkesin yaşama ...",Anayasanın 17. Maddesine aykırı değildir. Bu m...,chunk_000373,"Madde 17 – Herkes, yaşama, maddi ve manevi var..."
3,Geçici madde 20 ne zaman eklendi?,20 mayıs 2016 tarihinde.,"Geçici madde 20, Context 1'de belirtilen tarih...",chunk_000600,Madde 20- Açıklanması veya zamanından önce açı...
4,Videoda TCK 121 ihlali sabit değil mi?,Bu tür hususlar dosyalarında bilişimci bilirki...,"Gözlenen videoda, TCK 121 ihlali hakkında beli...",chunk_000101,Madde 121 – (Mülga: 21/1/2017-6771/16 md.) B. ...

In [38]:
strict_test_results = []

for _, row in test_eval_df.iterrows():
    question = row["question"]
    expected_answer = row["answer"]

    retrieved = hybrid_retrieve_top_k_filtered(
        question,
        embedding_model,
        index,
        chunks_df,
        bm25,
        k=5,
        alpha=0.5
    )

    contexts = [r["chunk_text"] for r in retrieved[:3]]
    prompt = build_strict_rag_prompt(question, contexts)
    generated_answer = generate_answer(prompt)

    strict_test_results.append({
        "question": question,
        "expected_answer": expected_answer,
        "generated_answer": generated_answer,
        "top1_chunk_id": retrieved[0]["chunk_id"],
        "top1_context": retrieved[0]["chunk_text"]
    })

strict_test_results_df = pd.DataFrame(strict_test_results)
strict_test_results_df.head()

,question,expected_answer,generated_answer,top1_chunk_id,top1_context
0,Anayasanın 101. Maddesiyle İlgili Tartışmalar ...,Cumhurbaşkanının seçilme şartlarının sınırları...,Sen Türk hukuk metinleri için çalışan dikkatli...,chunk_000210,Madde 158 – Uyuşmazlık Mahkemesi adli ve idari...
1,"Bir grup vatandaş, belirli bir etnik grubun di...","Anayasanın 10. Maddesi, herkesin kanun önünde ...",Sen Türk hukuk metinleri için çalışan dikkatli...,chunk_000188,"Madde 150 – Kanunların, Cumhurbaşkanlığı karar..."
2,"Bir grup akademisyen, yaşama hakkının sınırlan...","Evet, Anayasanın 17. Maddesi, herkesin yaşama ...",Sen Türk hukuk metinleri için çalışan dikkatli...,chunk_000373,"Madde 17 – Herkes, yaşama, maddi ve manevi var..."
3,Geçici madde 20 ne zaman eklendi?,20 mayıs 2016 tarihinde.,Sen Türk hukuk metinleri için çalışan dikkatli...,chunk_000600,Madde 20- Açıklanması veya zamanından önce açı...
4,Videoda TCK 121 ihlali sabit değil mi?,Bu tür hususlar dosyalarında bilişimci bilirki...,Sen Türk hukuk metinleri için çalışan dikkatli...,chunk_000101,Madde 121 – (Mülga: 21/1/2017-6771/16 md.) B. ...

In [39]:
base_test_results_df.to_csv(
    f"{project_path}/outputs/metrics/base_rag_testset_generation_results.csv",
    index=False,
    encoding="utf-8-sig"
)

strict_test_results_df.to_csv(
    f"{project_path}/outputs/metrics/strict_prompt_rag_testset_generation_results.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Test set generation results saved.")

Test set generation results saved.

In [40]:
for i, row in strict_test_results_df.iterrows():
    print("=" * 120)
    print("INDEX:", i)
    print("QUESTION:")
    print(row["question"])
    print("\nEXPECTED:")
    print(row["expected_answer"])
    print("\nGENERATED:")
    print(row["generated_answer"][:1000])

========================================================================================================================
INDEX: 0
QUESTION:
Anayasanın 101. Maddesiyle İlgili Tartışmalar Nelerdir?

EXPECTED:
Cumhurbaşkanının seçilme şartlarının sınırları ve uygulanması üzerine tartışmalar olabilir.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 158 – Uyuşmazlık Mahkemesi adli ve idari yargı mercileri arasındaki görev ve hüküm uyuşmazlıklarını kesin olarak çözümlemeye yetkilidir. [101]

[Context 2]
Madde 176 – Anayasanın dayandığı temel görüş ve ilkeleri belirten başlangıç kısmı, Anayasa metnine dahildir.

[Context 3]
Cumhurbaşkanlığı seçiminde birinci oylamada gerekli çoğunluğun sağlanamaması halinde 101 inci maddedeki usule göre ikinci oylama yapılır. D. Seçimlerin geriye bırakılması ve ara seçimler [34]

Soru:
Anayasanın 101. Maddesiyle İlgili Tartışmalar Nelerdir?

Kısa cevap:
Anayasanın 101. Maddesiyle ilgili tartışmalar, Uyuşmazlık Mahk
========================================================================================================================
INDEX: 1
QUESTION:
Bir grup vatandaş, belirli bir etnik grubun diğerlerinden daha fazla hakka sahip olması için imza kampanyası başlatmıştır. Bu durum Anayasanın 10. Maddesi ile nasıl çelişir?

EXPECTED:
Anayasanın 10. Maddesi, herkesin kanun önünde eşit olduğunu belirtir. Bu tür bir imza kampanyası Anayasa'ya aykırıdır.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 150 – Kanunların, Cumhurbaşkanlığı kararnamelerinin, Türkiye Büyük Millet Meclisi İçtüzüğünün veya bunların belirli madde ve hükümlerinin şekil ve esas bakımından Anayasaya aykırılığı iddiasıyla Anayasa Mahkemesinde doğrudan doğruya iptal davası açabilme hakkı, Cumhurbaşkanına, Türkiye Büyük Millet Meclisinde en fazla üyeye sahip iki siyasi parti grubuna ve üye tamsayısının en az beşte biri tutarındaki üyelere aittir. (Mülga son cümle: 21/1/2017-6771/16 md.) [91] 6. Dava açma süresi

[Context 2]
e) Anayasanın halkoylaması sonucu kabulünün ilanıyle birlikte yürürlüğe girecek hükümleri ve mevcut ve kuru
========================================================================================================================
INDEX: 2
QUESTION:
Bir grup akademisyen, yaşama hakkının sınırlanamayacağını savunmaktadır. Bu durum Anayasanın 17. Maddesi'ne aykırı mıdır?

EXPECTED:
Evet, Anayasanın 17. Maddesi, herkesin yaşama hakkına sahip olduğunu ve bu hakkın ancak kanunlarla düzenlenebileceğini belirtir. Bu tür bir savunma bu maddeye aykırıdır.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 17 – Herkes, yaşama, maddi ve manevi varlığını koruma ve geliştirme hakkına sahiptir.

[Context 2]
e) Anayasanın halkoylaması sonucu kabulünün ilanıyle birlikte yürürlüğe girecek hükümleri ve mevcut ve kurulacak kurum, kuruluş ve kurullar için yeniden kanun yapılması veya mevcut kanunlarda değişiklik yapılması gerekiyorsa bunlara ilişkin işlemler mevcut kanunların Anayasaya aykırı olmayan hükümleri veya doğrudan Anayasa hükümleri, Anayasanın 11 inci maddesi gereğince uygulanır.

[Context 3]
Madde 35 – Herkes, mülkiyet ve miras haklarına sahiptir. Bu haklar, ancak kamu yararı amacıyla, kanunla sınırlan
========================================================================================================================
INDEX: 3
QUESTION:
Geçici madde 20 ne zaman eklendi?

EXPECTED:
20 mayıs 2016 tarihinde.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 20- Açıklanması veya zamanından önce açıklanması hâlinde; a) Suç işlenmesine yol açacak,

[Context 2]
Madde 4 – (Mülga: 17/5/1987-3361/4 md.) [112] Geçici

[Context 3]
Madde 12 – 13/5/1981 gün ve 2461 sayılı Hakimler ve Savcılar Yüksek Kurulu Kanununun geçici 1 inci maddesi uyarınca Yargıtay ve Danıştaydan Kurulun asıl ve yedek üyeliğine; 1730 sayılı Yargıtay Kanununa 25/6/1981 gün ve 2483 sayılı Kanunla eklenen geçici madde uyarınca Cumhuriyet Başsavcılığı ile Cumhuriyet Başsavcıvekilliğine; 6/1/1982 gün ve 2575 sayılı Danıştay Kanununun geçici 14 üncü maddesinin ikinci fıkrası uyarınca Danıştay Başk
========================================================================================================================
INDEX: 4
QUESTION:
Videoda TCK 121 ihlali sabit değil mi?

EXPECTED:
Bu tür hususlar dosyalarında bilişimci bilirkişi raporu alınarak sonuca ulaşılabilir, bu şekilde değerlendirme yapılması hatalı olacaktır.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 121 – (Mülga: 21/1/2017-6771/16 md.) B. Sıkıyönetim, seferberlik ve savaş hali

[Context 2]
ÜÇÜNCÜ KISIM
Topluma Karşı Suçlar ALTINCI BÖLÜM
Ulaşım Araçlarına veya Sabit Platformlara Karşı Suçlar

[Context 3]
Arama Sonunda Verilecek Belge (Madde 121): Arama sonunda, hakkında arama yapılan kişiye, aramanın neden yapıldığı ve elkonulan eşya listesi gibi belgeler verilir.

Soru:
Videoda TCK 121 ihlali sabit değil mi?

Kısa cevap:
Hayır, TCK 121 ihlali sabit değildir. (Madde 121: B. Sıkıyönetim, seferberlik ve savaş hali)
========================================================================================================================
INDEX: 5
QUESTION:
Cumhurbaşkanının yemin etme zorunluluğu nedir

EXPECTED:
Cumhurbaşkanının yemin etme zorunluluğu, anayasa ve yasalara sadakatle bağlı kalacağını ve görevini tarafsız bir şekilde yürüteceğini taahhüt etmesini sağlar. yemin, cumhurbaşkanının görevine resmen başlaması için gereklidir.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Cumhurbaşkanı, ayrıca Anayasada ve kanunlarda verilen seçme ve atama görevleri ile diğer görevleri yerine getirir ve yetkileri kullanır. E. Cumhurbaşkanının cezai sorumluluğu [48]

[Context 2]
c) Cumhurbaşkanının istemine göre, iç ve dış güvenlik ile gerekli görülen diğer konularda inceleme ve araştırma yapmak ve sonuçlarını Cumhurbaşkanına sunmak. Geçici

[Context 3]
Cumhurbaşkanının hastalık ve yurt dışına çıkma gibi sebeplerle geçici olarak görevinden ayrılması hallerinde, Cumhurbaşkanı yardımcısı Cumhurbaşkanına vekâlet eder ve Cumhurbaşkanına ait yetkileri kullanır.

Soru:
Cumhurbaşkanının yemin etme z
========================================================================================================================
INDEX: 6
QUESTION:
Anayasanın 122. Maddesi Nedir?

EXPECTED:
Anayasanın 122. maddesi, sıkıyönetim ilanı ve yönetimine ilişkin hükümleri içerir.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 122 – (Mülga: 21/1/2017-6771/16 md.) Devamı…

[Context 2]
e) Anayasanın halkoylaması sonucu kabulünün ilanıyle birlikte yürürlüğe girecek hükümleri ve mevcut ve kurulacak kurum, kuruluş ve kurullar için yeniden kanun yapılması veya mevcut kanunlarda değişiklik yapılması gerekiyorsa bunlara ilişkin işlemler mevcut kanunların Anayasaya aykırı olmayan hükümleri veya doğrudan Anayasa hükümleri, Anayasanın 11 inci maddesi gereğince uygulanır.

[Context 3]
Madde 4 – Anayasanın 1 inci maddesindeki Devletin şeklinin Cumhuriyet olduğu hakkındaki hüküm ile, 2 nci maddesindeki Cumhuriyetin nitelikleri ve 3 üncü
========================================================================================================================
INDEX: 7
QUESTION:
Yasama dokunulmazlığının kaldırılmasına karşı itiraz süresi kaç gündür?

EXPECTED:
Yasama dokunulmazlığının kaldırılmasına veya milletvekilliğinin düşmesine 84 üncü maddenin birinci, üçüncü veya dördüncü fıkralarına göre karar verilmiş olması hallerinde, meclis genel kurulu kararının alındığı tarihten başlayarak yedi gün içerisinde ilgili milletvekili veya bir diğer milletvekili, kararın, anayasaya, kanuna veya i̇çtüzüğe aykırılığı iddiasıyla iptali için anayasa mahkemesine başvurabilir. anayasa mahkemesi, iptal istemini onbeş gün içerisinde kesin karara bağlar. (madde 85)

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Bu maddenin yürürlüğe girdiği tarihten itibaren onbeş gün içinde; Anayasa ve Adalet komisyonları üyelerinden kurulu Karma Komisyon Başkanlığında, Türkiye Büyük Millet Meclisi Başkanlığında, Başbakanlıkta ve Adalet Bakanlığında bulunan yasama dokunulmazlığının kaldırılmasına ilişkin dosyalar, gereğinin yapılması amacıyla, yetkili merciine iade edilir.

[Context 2]
Yasama dokunulmazlığının kaldırılmasına veya milletvekilliğinin düşmesine 84 üncü maddenin birinci, üçüncü veya dördüncü fıkralarına göre karar verilmiş olması hallerinde, Meclis Genel Kurulu kararının alındığı tarihten başlayarak yedi gün içerisin
========================================================================================================================
INDEX: 8
QUESTION:
Bir siyasi parti, çalışma şartlarının belirli durumlarda devlet tarafından keyfi olarak düzenlenebileceğini savunmaktadır. Bu durum Anayasanın 50. Maddesi'ne aykırı mıdır?

EXPECTED:
Evet, Anayasanın 50. Maddesi, herkesin çalışma şartları ve dinlenme hakkına sahip olduğunu belirtir. Bu tür bir savunma bu maddeye aykırıdır.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Siyasi partilerin faaliyetleri, parti içi düzenlemeleri ve çalışmaları demokrasi ilkelerine uygun olur. Bu ilkelerin uygulanması kanunla düzenlenir. Siyasi partiler, ticari faaliyetlere girişemezler.

[Context 2]
Madde 67 – Vatandaşlar, kanunda gösterilen şartlara uygun olarak seçme, seçilme ve bağımsız olarak veya bir siyasi parti içinde siyasi faaliyette bulunma ve halkoylamasına katılma hakkına sahiptir.

[Context 3]
Bir siyasi partinin 68 inci maddenin dördüncü fıkrası hükümlerine aykırı eylemlerinden ötürü temelli kapatılmasına, ancak, onun bu nitelikteki fiillerin işlendiği bir odak haline geldiğinin
========================================================================================================================
INDEX: 9
QUESTION:
Devlet Denetleme Kurulu, Silahlı Kuvvetler üzerinde denetim yapmıştır. Bu durum Anayasanın 108. Maddesi ile nasıl çelişir?

EXPECTED:
Anayasanın 108. Maddesi, Silahlı Kuvvetlerin Devlet Denetleme Kurulu'nun denetiminin dışında olduğunu belirtir. Bu durum maddeye aykırıdır.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 107 – (Mülga: 21/1/2017-6771/16 md.) H. Devlet Denetleme Kurulu

[Context 2]
Madde 108 – İdarenin hukuka uygunluğunun, düzenli ve verimli şekilde yürütülmesinin ve geliştirilmesinin sağlanması amacıyla, Cumhurbaşkanlığına bağlı olarak kurulan Devlet Denetleme Kurulu, Cumhurbaşkanının isteği üzerine, tüm kamu kurum ve kuruluşlarında ve sermayesinin yarısından fazlasına bu kurum ve kuruluşların katıldığı her türlü kuruluşta, kamu kurumu niteliğinde olan meslek kuruluşlarında, her düzeydeki işçi ve işveren meslek kuruluşlarında, kamuya yararlı derneklerle vakıflarda, her türlü idari soruşturma, inceleme,
========================================================================================================================
INDEX: 10
QUESTION:
Bir belediye, yerel yönetimde temel hak ve hürriyetlerin keyfi olarak sınırlandırılmasını kararlaştırmıştır. Bu uygulama Anayasanın 13. Maddesi'ne aykırı mıdır?

EXPECTED:
Evet, Anayasanın 13. Maddesi, temel hak ve hürriyetlerin ancak kanunla ve Anayasanın sözüne ve ruhuna uygun olarak sınırlandırılabileceğini vurgular. Keyfi sınırlandırmalar bu maddeye aykırıdır.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Anayasa hükümlerinden hiçbiri, Devlete veya kişilere, Anayasayla tanınan temel hak ve hürriyetlerin yok edilmesini veya Anayasada belirtilenden daha geniş şekilde sınırlandırılmasını amaçlayan bir faaliyette bulunmayı mümkün kılacak şekilde yorumlanamaz. Bu hükümlere aykırı faaliyette bulunanlar hakkında uygulanacak müeyyideler, kanunla düzenlenir. I V. Temel hak ve hürriyetlerin kullanılmasının durdurulması

[Context 2]
Temel hak ve hürriyetler, özlerine dokunulmaksızın yalnızca Anayasanın ilgili maddelerinde belirtilen sebeplere bağlı olarak ve ancak kanunla sınırlanabilir. Bu sınırlamalar, Anayasanın söz
========================================================================================================================
INDEX: 11
QUESTION:
İlgili kişi ne demektir?

EXPECTED:
Kişisel verisi işlenen gerçek kişi demektir.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 8 – (1) Bir kişi, birden fazla suçtan sanık olur veya bir suçta her ne sıfatla olursa olsun birden fazla sanık bulunursa bağlantı var sayılır.

[Context 2]
Şüpheli veya Sanıkla İlgili Arama (Madde 116): Makul şüphe varsa, şüphelinin veya sanığın üstü, eşyası, konutu, işyeri veya diğer yerleri aranabilir.

[Context 3]
Diğer Kişilerle İlgili Arama (Madde 117): Şüpheli veya sanığın yakalanabilmesi ya da suç delillerinin elde edilebilmesi için, başka kişilerin de üstü, eşyası, konutu veya işyerleri aranabilir. Bu aramalar, sadece olayların aramanın yapılacağı yerle bağlantılı olduğu durumlarda geçerlidir.
========================================================================================================================
INDEX: 12
QUESTION:
Anayasa mahkemesi kararlarının kesinliği nedir

EXPECTED:
Anayasa mahkemesi kararlarının kesinliği, mahkemenin verdiği kararların nihai ve değiştirilemez olduğu anlamına gelir. bu kararlar, başka bir yargı merci tarafından bozulamaz veya yeniden incelenemez.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Diğer mahkemelerle, Anayasa Mahkemesi arasındaki görev uyuşmazlıklarında, Anayasa Mahkemesinin kararı esas alınır.
Devamı…

[Context 2]
Kanun, Cumhurbaşkanlığı kararnamesi veya Türkiye Büyük Millet Meclisi İçtüzüğü ya da bunların hükümleri, iptal kararlarının Resmî Gazetede yayımlandığı tarihte yürürlükten kalkar. Gereken hallerde Anayasa Mahkemesi iptal hükmünün yürürlüğe gireceği tarihi ayrıca kararlaştırabilir. Bu tarih, kararın Resmî Gazetede yayımlandığı günden başlayarak bir yılı geçemez. [95]

[Context 3]
Anayasa Mahkemesi üyeliği, bir üyenin hakimlik mesleğinden çıkarılmayı gerektiren bir suçtan dol
========================================================================================================================
INDEX: 13
QUESTION:
Anayasa madde 63'e göre, tarih, kültür ve tabiat varlıklarının korunması nasıl sağlanır?

EXPECTED:
Anayasa madde 63'e göre, devlet, tarih, kültür ve tabiat varlıklarının ve değerlerinin korunmasını sağlar ve bu amaçla destekleyici ve teşvik edici tedbirleri alır.

GENERATED:
Sen Türk hukuk metinleri için çalışan dikkatli bir soru-cevap asistanısın.

Kurallar:
- Cevabı SADECE verilen bağlama göre ver.
- Bağlamda açıkça yazmayan çıkarımları yapma.
- Birden fazla bağlam çelişirse en doğrudan cevap veren bağlamı kullan.
- Cevap Türkçe olmalı.
- Cevap kısa ve net olmalı.
- İngilizce açıklama, "Therefore", "Context 1" gibi ifadeler yazma.

Bağlam:
[Context 1]
Madde 63 – Devlet, tarih, kültür ve tabiat varlıklarının ve değerlerinin korunmasını sağlar, bu amaçla destekleyici ve teşvik edici tedbirleri alır.

[Context 2]
Madde 62 – Devlet, yabancı ülkelerde çalışan Türk vatandaşlarının aile birliğinin, çocuklarının eğitiminin, kültürel ihtiyaçlarının ve sosyal güvenliklerinin sağlanması, anavatanla bağlarının korunması ve yurda dönüşlerinde yardımcı olunması için gereken tedbirleri alır. X I. Tarih, kültür ve tabiat varlıklarının korunması

[Context 3]
Madde 129 – Memurlar ve diğer kamu görevlileri Anayasa ve kanunlara sadık kalarak faaliyette bulunmakla yükümlüdür
========================================================================================================================
INDEX: 14
QUESTION:
Anayasa madde 47, devletleştirme ve özelleştirme işlemlerinin korunması için ne tür tedbirler alınacağını düzenler

EXPECTED:

In [41]:
def clean_generated_answer(text):
    text = str(text)

    if "Kısa cevap:" in text:
        text = text.split("Kısa cevap:")[-1].strip()

    if "Detaylı cevap:" in text:
        text = text.split("Detaylı cevap:")[0].strip()

    return text.strip()

strict_test_results_df["clean_generated_answer"] = strict_test_results_df["generated_answer"].apply(clean_generated_answer)

In [42]:
for i, row in strict_test_results_df.iterrows():
    print("=" * 120)
    print("INDEX:", i)
    print("QUESTION:")
    print(row["question"])
    print("\nEXPECTED:")
    print(row["expected_answer"])
    print("\nCLEAN GENERATED:")
    print(row["clean_generated_answer"][:1000])

========================================================================================================================
INDEX: 0
QUESTION:
Anayasanın 101. Maddesiyle İlgili Tartışmalar Nelerdir?

EXPECTED:
Cumhurbaşkanının seçilme şartlarının sınırları ve uygulanması üzerine tartışmalar olabilir.

CLEAN GENERATED:
Anayasanın 101. Maddesiyle ilgili tartışmalar, Uyuşmazlık Mahkemesi adli ve idari yargı mercileri arasındaki görev ve hüküm uyuşmazlıklarının çözülmesi hakkındadır.
========================================================================================================================
INDEX: 1
QUESTION:
Bir grup vatandaş, belirli bir etnik grubun diğerlerinden daha fazla hakka sahip olması için imza kampanyası başlatmıştır. Bu durum Anayasanın 10. Maddesi ile nasıl çelişir?

EXPECTED:
Anayasanın 10. Maddesi, herkesin kanun önünde eşit olduğunu belirtir. Bu tür bir imza kampanyası Anayasa'ya aykırıdır.

CLEAN GENERATED:
Anayasanın 10. Maddesi, Türkiye'nin bütün vatandaşlarının halkoyluğunu temsil etmesine dayalı olarak, Cumhurbaşkanına, Türkiye Büyük Millet Meclisinde en fazla üyeye sahip iki siyasi parti grubuna ve üye tamsayısının en az beşte biri tutarındaki üyelere ait hakkı tanımlar. Bu durumda, etnik grubunun diğerlerinden daha fazla hak sahibi olduğu durum, Anayasanın 15. Maddesi
========================================================================================================================
INDEX: 2
QUESTION:
Bir grup akademisyen, yaşama hakkının sınırlanamayacağını savunmaktadır. Bu durum Anayasanın 17. Maddesi'ne aykırı mıdır?

EXPECTED:
Evet, Anayasanın 17. Maddesi, herkesin yaşama hakkına sahip olduğunu ve bu hakkın ancak kanunlarla düzenlenebileceğini belirtir. Bu tür bir savunma bu maddeye aykırıdır.

CLEAN GENERATED:
Hayat hakkının sınırlanamayacağını savunmak, Anayasanın 17. Maddesine aykırı değildir. Bu durum, Anayasanın 11. inci maddesine uyacak şekilde, yani kamu yararına yönelik olmalıdır.
========================================================================================================================
INDEX: 3
QUESTION:
Geçici madde 20 ne zaman eklendi?

EXPECTED:
20 mayıs 2016 tarihinde.

CLEAN GENERATED:
Geçici madde 20 17/5/1987 tarihinde eklendi.
========================================================================================================================
INDEX: 4
QUESTION:
Videoda TCK 121 ihlali sabit değil mi?

EXPECTED:
Bu tür hususlar dosyalarında bilişimci bilirkişi raporu alınarak sonuca ulaşılabilir, bu şekilde değerlendirme yapılması hatalı olacaktır.

CLEAN GENERATED:
Hayır, TCK 121 ihlali sabit değildir. (Madde 121: B. Sıkıyönetim, seferberlik ve savaş hali)
========================================================================================================================
INDEX: 5
QUESTION:
Cumhurbaşkanının yemin etme zorunluluğu nedir

EXPECTED:
Cumhurbaşkanının yemin etme zorunluluğu, anayasa ve yasalara sadakatle bağlı kalacağını ve görevini tarafsız bir şekilde yürüteceğini taahhüt etmesini sağlar. yemin, cumhurbaşkanının görevine resmen başlaması için gereklidir.

CLEAN GENERATED:
Cumhurbaşkanının yemin etme zorunluluğu, Anayasada ve kanunlarda verilen seçme ve atama görevleri ile diğer görevleri yerine getirme ve yetkileri kullanma hakkıdır. (Context 1)
========================================================================================================================
INDEX: 6
QUESTION:
Anayasanın 122. Maddesi Nedir?

EXPECTED:
Anayasanın 122. maddesi, sıkıyönetim ilanı ve yönetimine ilişkin hükümleri içerir.

CLEAN GENERATED:
Anayasanın 122. Maddesi, halkoylaması sonucu kabul edilenecek hükümlerin ve mevcut ve kurulacak kurum, kuruluş ve kurullar için yeniden kanun yapılması veya mevcut kanunlarda değişiklik yapılması gereken durumlara ilişkin işlemlerin Anayasaya aykırı olmayan hükümleri veya doğrudan Anayasa hükümleri, Anayasanın 11 inci maddesi gereğince uygulanmasına ilişkin bir madded
========================================================================================================================
INDEX: 7
QUESTION:
Yasama dokunulmazlığının kaldırılmasına karşı itiraz süresi kaç gündür?

EXPECTED:
Yasama dokunulmazlığının kaldırılmasına veya milletvekilliğinin düşmesine 84 üncü maddenin birinci, üçüncü veya dördüncü fıkralarına göre karar verilmiş olması hallerinde, meclis genel kurulu kararının alındığı tarihten başlayarak yedi gün içerisinde ilgili milletvekili veya bir diğer milletvekili, kararın, anayasaya, kanuna veya i̇çtüzüğe aykırılığı iddiasıyla iptali için anayasa mahkemesine başvurabilir. anayasa mahkemesi, iptal istemini onbeş gün içerisinde kesin karara bağlar. (madde 85)

CLEAN GENERATED:
Yasama dokunulmazlığının kaldırılmasına karşı itiraz sürecinin sınırı yedi gün'dur. (Context 2)
========================================================================================================================
INDEX: 8
QUESTION:
Bir siyasi parti, çalışma şartlarının belirli durumlarda devlet tarafından keyfi olarak düzenlenebileceğini savunmaktadır. Bu durum Anayasanın 50. Maddesi'ne aykırı mıdır?

EXPECTED:
Evet, Anayasanın 50. Maddesi, herkesin çalışma şartları ve dinlenme hakkına sahip olduğunu belirtir. Bu tür bir savunma bu maddeye aykırıdır.

CLEAN GENERATED:
Anayasanın 50. Maddesi, siyasi partilerin halkoylamasına ve seçim hakkına ilişkin yasal kısımların uygulanmasını sadece devlet tarafından düzenlemeye izin verir. Parti çalışma şartlarının belirli durumlarda devlet tarafından keyfi olarak düzenlenebilmesi, Anayasanın 50. Maddesine aykırı değildir. (Bağlam: [Context 1], [Context 2], [Context 3])
========================================================================================================================
INDEX: 9
QUESTION:
Devlet Denetleme Kurulu, Silahlı Kuvvetler üzerinde denetim yapmıştır. Bu durum Anayasanın 108. Maddesi ile nasıl çelişir?

EXPECTED:
Anayasanın 108. Maddesi, Silahlı Kuvvetlerin Devlet Denetleme Kurulu'nun denetiminin dışında olduğunu belirtir. Bu durum maddeye aykırıdır.

CLEAN GENERATED:
Anayasanın 108. Maddesi, Devlet Denetleme Kurulu'nun yürütülecek hukuka uygunluğunu, düzenli ve verimli şekilde yürütülmesini ve geliştirilmesini sağlayan rolunu belirten bir maddedir. Bu rol, Devlet Denetleme Kurulu'nun Silahlı Kuvvetler üzerinde denetim yapmasının hukuka uygun olduğunu ve gereksiz olmayan sınırlamaların yerine getirilmediğini ifade eder. Bu nedenle, Anayasanı
========================================================================================================================
INDEX: 10
QUESTION:
Bir belediye, yerel yönetimde temel hak ve hürriyetlerin keyfi olarak sınırlandırılmasını kararlaştırmıştır. Bu uygulama Anayasanın 13. Maddesi'ne aykırı mıdır?

EXPECTED:
Evet, Anayasanın 13. Maddesi, temel hak ve hürriyetlerin ancak kanunla ve Anayasanın sözüne ve ruhuna uygun olarak sınırlandırılabileceğini vurgular. Keyfi sınırlandırmalar bu maddeye aykırıdır.

CLEAN GENERATED:
Anayasanın 13. Maddesi, temel hak ve hürriyetlerin yok edilmesini veya Anayasada belirtilenden daha geniş şekilde sınırlandırılmasını mümkün kılmayan bir faaliyette bulunmayı mümkün değil. Bu nedenle, belediye tarafından temel hak ve hürriyetlerin keyfi olarak sınırlandırılması Anayasanın 13. Maddesine aykırı olabilir.
========================================================================================================================
INDEX: 11
QUESTION:
İlgili kişi ne demektir?

EXPECTED:
Kişisel verisi işlenen gerçek kişi demektir.

CLEAN GENERATED:
İlgili kişi, şüpheli veya sanığın anlamına göre, yani şüpheli kişi veya sanık hakkında ilgili olan kişilere denir.
========================================================================================================================
INDEX: 12
QUESTION:
Anayasa mahkemesi kararlarının kesinliği nedir

EXPECTED:
Anayasa mahkemesi kararlarının kesinliği, mahkemenin verdiği kararların nihai ve değiştirilemez olduğu anlamına gelir. bu kararlar, başka bir yargı merci tarafından bozulamaz veya yeniden incelenemez.

CLEAN GENERATED:
Anayasa Mahkemesi kararları, Anayasa Mahkemesi üyelerinin tamsayısının salt çoğunluğunun kararı ile sona erir. Bu, bir üyenin hakimlik mesleğinden çıkarılmayı gerektiren bir suçtan dolayı kendiliğinden hüküm giymesine rağmen, sağlık bakımından yerine getiremeyeceğinin kesin olarak anlaşılması halinde geçerlidir. (Context 3)
========================================================================================================================
INDEX: 13
QUESTION:
Anayasa madde 63'e göre, tarih, kültür ve tabiat varlıklarının korunması nasıl sağlanır?

EXPECTED:
Anayasa madde 63'e göre, devlet, tarih, kültür ve tabiat varlıklarının ve değerlerinin korunmasını sağlar ve bu amaçla destekleyici ve teşvik edici tedbirleri alır.

CLEAN GENERATED:
Anayasa Madde 63'e göre, devlet tarih, kültür ve tabiat varlıklarının ve değerlerinin korunmasını sağlar, bu amaçla destekleyici ve teşvik edici tedbirleri alır.
========================================================================================================================
INDEX: 14
QUESTION:
Anayasa madde 47, devletleştirme ve özelleştirme işlemlerinin korunması için ne tür tedbirler alınacağını düzenler

EXPECTED:
Anayasa madde 47, devletleştirme ve özelleştirme işlemlerinin korunması için devletin, bu işlemleri anayasal ve kanuni düzenlemelere uygun olarak gerçekleştirmesini düzenler. devlet, devletleştirme ve özelleştirme işlemlerini adil ve hukuka uygun olarak gerçekleştirmek zorundadır.

CLEAN GENERATED:
Anayasa Madde 47, kamu hizmeti niteliği taşınan özel teşebbüslerin devletleştirilmesi için gerçek karşılığın hesaplanmasının kanunla düzenlenmesine dayalı tedbirler alınır. Bu tedbirler, ikinci fikradaki taksitlendirmelerde ve herhangi bir sebeple ödenmemiş kamulaştırma bedellerinde kamu alacakları için en yüksek faiz uygulanmasını gibi belirtilmektedir. (Madde 47, Context
========================================================================================================================
INDEX: 15
QUESTION:
Kişisel veriler hangi mevzuata göre işlenir?

EXPECTED:
Kvk kanununda ve diğer kanunlarda öngörülen mevzuata göre işlenir.

CLEAN GENERATED:
Kişisel veriler, kanunla düzenlenir. (B. Konut dokunulmazlığı, Madde 42)
========================================================================================================================
INDEX: 16
QUESTION:
Anayasa madde 140'a göre, hakimlerin ve savcıların görev ve yetkileri nasıl düzenlenir?

EXPECTED:
Anayasa madde 140'a göre, hakimlerin ve savcıların görev ve yetkileri, çalışma usulleri, mesleğe kabul, atanma, nakil, geçici yetki verme, yükselme, aylık, ödenek ve diğer özlük işleri, meslek içi eğitim, görevden uzaklaştırılma, emeklilik ve disiplin işlerine ilişkin esaslar kanunla düzenlenir.

CLEAN GENERATED:
Anayasa Madde 140'da, hakimler ve savcıların görevleri ve yetkileri meslekten yürütülür. Hakimler, mahkemelerin bağımsızlığı ve hakimlik teminatı esaslarına göre görev ifa ederler. Kanunla düzenlenmeyen şekilde, bu görevler hakkında daha fazla bilgi için [Context 1] ve [Context 2] inceleyebilirsiniz.
========================================================================================================================
INDEX: 17
QUESTION:
Ekonomik ve sosyal konsey hangi anayasa maddesi ile düzenlenmiştir

EXPECTED:
Ekonomik ve sosyal konsey, türkiye cumhuriyeti anayasası'nın 115. maddesi ile düzenlenmiştir. bu madde, konseyi ve görevlerini belirler.

CLEAN GENERATED:
Anayasa ile belirlenen görevlerini, bu görevlerin amaçlarına uygun öncelikleri gözeterek malî kaynaklarının yeterliliği ölçüsünde yerine getirir. (Anayasa maddesi ile ilgili bilgi yoktur.)
========================================================================================================================
INDEX: 18
QUESTION:
Bilgi edinme hakkının ihlali durumunda ne yapılabilir

EXPECTED:
Bilgi edinme hakkının ihlali durumunda, bireyler bilgi edinme değerlendirme kurulu'na başvurarak ihlalin durdurulmasını ve talep ettikleri bilgilere erişim sağlanmasını isteyebilirler.

CLEAN GENERATED:
Bilgi edinme hakkının ihlali durumunda, Bilgi Edinme Değerlendirme Kurulu tarafından kararlar verilir.
========================================================================================================================
INDEX: 19
QUESTION:
İdari yargı nedir?

EXPECTED:
Hukuki dinlenilme hakkı, tarafların yargılama sürecinde savunmalarını yapabilme ve delillerini sunabilme hakkıdır.

CLEAN GENERATED:
Idari yargı, yönetim görevleri yürütülmesi ve ilgili kararları verilmesi için kurulan bir yüksek organidir. (Context 3)

In [43]:
strict_test_results_df["is_valid_sample"] = True

# Dataset hatalı/uyumsuz sample
strict_test_results_df.loc[19, "is_valid_sample"] = False

manual_scores_strict = [
    0.0,  # 0 - yanlış context / yanlış cevap
    0.0,  # 1 - yanlış
    0.5,  # 2 - kısmen, yaşama hakkını yakalamış ama aykırılık yorumu ters
    0.0,  # 3 - yanlış tarih
    0.0,  # 4 - yanlış / alakasız
    0.0,  # 5 - yanlış
    0.0,  # 6 - yanlış/eksik
    1.0,  # 7 - yedi gün doğru
    0.0,  # 8 - yanlış
    0.0,  # 9 - yanlış
    0.5,  # 10 - kısmen doğru
    0.0,  # 11 - yanlış
    0.0,  # 12 - yanlış
    1.0,  # 13 - doğru
    0.5,  # 14 - kısmen doğru
    0.5,  # 15 - kısmen doğru
    0.5,  # 16 - kısmen doğru
    0.0,  # 17 - yanlış / cevap yok
    0.5,  # 18 - kısmen doğru
    0.0   # 19 - invalid olacak, skora katılmayacak
]

strict_test_results_df["manual_score"] = manual_scores_strict

valid_strict_df = strict_test_results_df[strict_test_results_df["is_valid_sample"] == True]

strict_test_score = valid_strict_df["manual_score"].mean()

print("Strict Prompt RAG Test Score:", strict_test_score)
print("Valid sample count:", len(valid_strict_df))

Strict Prompt RAG Test Score: 0.2631578947368421
Valid sample count: 19

In [44]:
strict_test_results_df.to_csv(
    f"{project_path}/outputs/metrics/strict_prompt_rag_testset_scored.csv",
    index=False,
    encoding="utf-8-sig"
)

pd.DataFrame([{
    "method": "Strict Prompt RAG - Hybrid Retrieval + Base LLM",
    "manual_accuracy": strict_test_score,
    "valid_sample_count": len(valid_strict_df),
    "total_sample_count": len(strict_test_results_df)
}]).to_csv(
    f"{project_path}/outputs/metrics/strict_prompt_rag_testset_score.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Strict prompt test score saved.")

Strict prompt test score saved.

In [45]:
base_test_results = []

for _, row in test_eval_df.iterrows():
    question = row["question"]
    expected_answer = row["answer"]

    retrieved = hybrid_retrieve_top_k_filtered(
        question,
        embedding_model,
        index,
        chunks_df,
        bm25,
        k=5,
        alpha=0.5
    )

    contexts = [r["chunk_text"] for r in retrieved[:3]]

    # 👇 BASE PROMPT (eski)
    prompt = build_rag_prompt(question, contexts)

    generated_answer = generate_answer(prompt)

    base_test_results.append({
        "question": question,
        "expected_answer": expected_answer,
        "generated_answer": generated_answer
    })

base_test_results_df = pd.DataFrame(base_test_results)

In [46]:
base_test_results_df["clean_generated_answer"] = base_test_results_df["generated_answer"].apply(clean_generated_answer)

In [47]:
for i, row in base_test_results_df.iterrows():
    print("=" * 120)
    print("INDEX:", i)
    print("QUESTION:")
    print(row["question"])
    print("\nEXPECTED:")
    print(row["expected_answer"])
    print("\nCLEAN GENERATED:")
    print(row["clean_generated_answer"][:500])

========================================================================================================================
INDEX: 0
QUESTION:
Anayasanın 101. Maddesiyle İlgili Tartışmalar Nelerdir?

EXPECTED:
Cumhurbaşkanının seçilme şartlarının sınırları ve uygulanması üzerine tartışmalar olabilir.

CLEAN GENERATED:
Anayasanın 101. Madde'si, Uyuşmazlık Mahkemesi'nin görevi olan adli ve idari yargı mercileri arasındaki görev ve hüküm uyuşmazlıklarını kesin olarak çözümlemeye yetkilidir. Bu konuda tartışılabilen temel sorunlar, Uyuşmazlık Mahkemesi'nin görevleri, hüküm verme yetkisini taşıyan kişinin hangi kurumda bulunur, ve bu yetkisini kullanan kişinin ne tür hüküm
========================================================================================================================
INDEX: 1
QUESTION:
Bir grup vatandaş, belirli bir etnik grubun diğerlerinden daha fazla hakka sahip olması için imza kampanyası başlatmıştır. Bu durum Anayasanın 10. Maddesi ile nasıl çelişir?

EXPECTED:
Anayasanın 10. Maddesi, herkesin kanun önünde eşit olduğunu belirtir. Bu tür bir imza kampanyası Anayasa'ya aykırıdır.

CLEAN GENERATED:
Bu durum Anayasanın 150. Madde ile ilgili olabilir. Bu madde, Anayasanın 10. Maddesine karşı, Cumhurbaşkanına ve Türkiye Büyük Millet Meclisinde en fazla üyeye sahip iki siyasi parti grubuna ve üye tamsayısının en az beşte birisi tutarak, doğrudan Anayasaya iddiasıyla Anayasa Mahkemesinde doğrudan doğruya iptal davası açabilen haklar vermektedir. Bu grup vatandaşın etnik grubunun diğ
========================================================================================================================
INDEX: 2
QUESTION:
Bir grup akademisyen, yaşama hakkının sınırlanamayacağını savunmaktadır. Bu durum Anayasanın 17. Maddesi'ne aykırı mıdır?

EXPECTED:
Evet, Anayasanın 17. Maddesi, herkesin yaşama hakkına sahip olduğunu ve bu hakkın ancak kanunlarla düzenlenebileceğini belirtir. Bu tür bir savunma bu maddeye aykırıdır.

CLEAN GENERATED:
Anayasanın 17. Maddesine aykırı değildir. Bu maddenin içeriği, herkesin yaşama, maddi ve manevi varlığını koruma ve geliştirme hakkını ifade ediyor. Akademisyenin yaşama hakkının sınırlanamayacağını savunmak, bu hakın kendisini koruma ve geliştirme konusunda olduğu gibi, Anayasanın 17. Maddesine uygun olacaktır.
========================================================================================================================
INDEX: 3
QUESTION:
Geçici madde 20 ne zaman eklendi?

EXPECTED:
20 mayıs 2016 tarihinde.

CLEAN GENERATED:
Geçici madde 20, Context 1'de belirtilen tarihde eklendi. Ancak, tarih belirtilmemiştir. Bu nedenle, tarihi anlamında geçici madde 20'nin eklendiği tarih bilinememektedir. (The answer cannot be found in the given context.)
========================================================================================================================
INDEX: 4
QUESTION:
Videoda TCK 121 ihlali sabit değil mi?

EXPECTED:
Bu tür hususlar dosyalarında bilişimci bilirkişi raporu alınarak sonuca ulaşılabilir, bu şekilde değerlendirme yapılması hatalı olacaktır.

CLEAN GENERATED:
Gözlenen videoda, TCK 121 ihlali hakkında belirtilmez. Bu konuda, Context1'deki Madde 121 hakkında bilgi verilmiştir. Ancak, videoda TCK 121'nin ihlali hakkında bilgi verilmemiştir. Bu nedenle, videoda TCK 121 ihlali sabit değil olabilip olmayabilir anlamına verilemez. (Answer in Turkish: Videodaki TCK 121 ihlali sabit değil mi, bu konuda videodaki bilgi verilmemiştir. Bu nedenle, videoda T
========================================================================================================================
INDEX: 5
QUESTION:
Cumhurbaşkanının yemin etme zorunluluğu nedir

EXPECTED:
Cumhurbaşkanının yemin etme zorunluluğu, anayasa ve yasalara sadakatle bağlı kalacağını ve görevini tarafsız bir şekilde yürüteceğini taahhüt etmesini sağlar. yemin, cumhurbaşkanının görevine resmen başlaması için gereklidir.

CLEAN GENERATED:
Cumhurbaşkanın yemin etme zorunluluğu hakkında context'da ifade edilmiyor. (The context does not mention Cumhurbaşkanı's swearing-in requirement.)
========================================================================================================================
INDEX: 6
QUESTION:
Anayasanın 122. Maddesi Nedir?

EXPECTED:
Anayasanın 122. maddesi, sıkıyönetim ilanı ve yönetimine ilişkin hükümleri içerir.

CLEAN GENERATED:
Anayasının 122. Madde hakkında, Context 1'de belirtilmiştir. Bu madde, Mülga Tarihinde 21/1/2017 tarihli ve 6771/16 sayılı md. ile yürürlüğe girdi. Ayrıca, bu madde, mevcut ve kurulacak kurum, kuruluş ve kurullar için yeniden kanun yapılması veya mevcut kanunlarda değişiklik yapılması gereken hükümleri ve Anayasaya aykırı olmayan hükümler
========================================================================================================================
INDEX: 7
QUESTION:
Yasama dokunulmazlığının kaldırılmasına karşı itiraz süresi kaç gündür?

EXPECTED:
Yasama dokunulmazlığının kaldırılmasına veya milletvekilliğinin düşmesine 84 üncü maddenin birinci, üçüncü veya dördüncü fıkralarına göre karar verilmiş olması hallerinde, meclis genel kurulu kararının alındığı tarihten başlayarak yedi gün içerisinde ilgili milletvekili veya bir diğer milletvekili, kararın, anayasaya, kanuna veya i̇çtüzüğe aykırılığı iddiasıyla iptali için anayasa mahkemesine başvurabilir. anayasa mahkemesi, iptal istemini onbeş gün içerisinde kesin karara bağlar. (madde 85)

CLEAN GENERATED:
The legal context does not provide information on the duration of the objection period against the removal of immunity from prosecution. Therefore, the answer cannot be found in the given context.
========================================================================================================================
INDEX: 8
QUESTION:
Bir siyasi parti, çalışma şartlarının belirli durumlarda devlet tarafından keyfi olarak düzenlenebileceğini savunmaktadır. Bu durum Anayasanın 50. Maddesi'ne aykırı mıdır?

EXPECTED:
Evet, Anayasanın 50. Maddesi, herkesin çalışma şartları ve dinlenme hakkına sahip olduğunu belirtir. Bu tür bir savunma bu maddeye aykırıdır.

CLEAN GENERATED:
Anayasanın 50. Maddesi, siyasi partilerin faaliyetleri, parti içi düzenlemeleri ve çalışmaları demokrasi ilkelerine uygun olmasını söylar. Parti, devlet tarafından keyfi olarak çalışma şartlarını düzenlemesine izin verebilirse, bu, Anayasanın 50. Maddesine uyumu sağlar. (Context 1 ve Context 3'ten görüldüğü gibi, kanunla düzenlenmiş demokrasi ilkeleri içerisinde siyasi
========================================================================================================================
INDEX: 9
QUESTION:
Devlet Denetleme Kurulu, Silahlı Kuvvetler üzerinde denetim yapmıştır. Bu durum Anayasanın 108. Maddesi ile nasıl çelişir?

EXPECTED:
Anayasanın 108. Maddesi, Silahlı Kuvvetlerin Devlet Denetleme Kurulu'nun denetiminin dışında olduğunu belirtir. Bu durum maddeye aykırıdır.

CLEAN GENERATED:
Anayasanın 108. Madde, Cumhurbaşkanlığına bağlı olarak kurulan Devlet Denetleme Kurulu (DDK) hakkında söylenmektedir. Bu madde, DDK'nin her türlü idari soruşturma, inceleme, araştırma ve denetleme yapma hakkını sınırlar. Silahlı Kuvvetler üzerinde denetim yapmak, DDK'nin görev alanına ait olduğu için, Anayasanın 108. Madde ile çeli
========================================================================================================================
INDEX: 10
QUESTION:
Bir belediye, yerel yönetimde temel hak ve hürriyetlerin keyfi olarak sınırlandırılmasını kararlaştırmıştır. Bu uygulama Anayasanın 13. Maddesi'ne aykırı mıdır?

EXPECTED:
Evet, Anayasanın 13. Maddesi, temel hak ve hürriyetlerin ancak kanunla ve Anayasanın sözüne ve ruhuna uygun olarak sınırlandırılabileceğini vurgular. Keyfi sınırlandırmalar bu maddeye aykırıdır.

CLEAN GENERATED:
Bu sorunun cevabı, Anayasanın 13. Maddesine aykırı olup olmadığını anlamak için, Anayasanın 13. Maddesi hakkındaki yasal kısımların içeriğine bakmamız gerekir. Bu sorunun cevabı, bu konu hakkında Anayasada belirtilmemiştir. Bu nedenle, Anayasanın 13. Maddesi'ne aykırı olup olmadığı cevabı verilemez. (The answer to this question cannot be found in the given context.)
========================================================================================================================
INDEX: 11
QUESTION:
İlgili kişi ne demektir?

EXPECTED:
Kişisel verisi işlenen gerçek kişi demektir.

CLEAN GENERATED:
İlgili kişi, contextte verilmiştir ki, birden fazla suçtan bir kişi olup bununla ilgili bir şüphe varsa veya bir sanık olduğu durumda, bağlantılı kişi anlamına gelmektedir. (Related person refers to a person who is suspected of multiple crimes or is a suspect, and there is a connection between them.)
========================================================================================================================
INDEX: 12
QUESTION:
Anayasa mahkemesi kararlarının kesinliği nedir

EXPECTED:
Anayasa mahkemesi kararlarının kesinliği, mahkemenin verdiği kararların nihai ve değiştirilemez olduğu anlamına gelir. bu kararlar, başka bir yargı merci tarafından bozulamaz veya yeniden incelenemez.

CLEAN GENERATED:
Anayasa Mahkemesi kararları, Anayasa Mahkemesi üye tamsayısının salt çoğunluğunun kararıyla sona erir. (Context 3)

Therefore, the definiteness of Anayasa Mahkemesi (Constitutional Court) judgments is determined by the majority of its members.
========================================================================================================================
INDEX: 13
QUESTION:
Anayasa madde 63'e göre, tarih, kültür ve tabiat varlıklarının korunması nasıl sağlanır?

EXPECTED:
Anayasa madde 63'e göre, devlet, tarih, kültür ve tabiat varlıklarının ve değerlerinin korunmasını sağlar ve bu amaçla destekleyici ve teşvik edici tedbirleri alır.

CLEAN GENERATED:
Madde 63, devlet, tarih, kültür ve tabiat varlıklarının ve değerlerinin korunmasına olanak tanır. Bu amaçla destekleyici ve teşvik edici tedbirler alınır. (Context 1)

Therefore, according to Article 63 of the Constitution, the protection of cultural, historical, and natural assets is achieved through supportive and facilitating measures.
========================================================================================================================
INDEX: 14
QUESTION:
Anayasa madde 47, devletleştirme ve özelleştirme işlemlerinin korunması için ne tür tedbirler alınacağını düzenler

EXPECTED:
Anayasa madde 47, devletleştirme ve özelleştirme işlemlerinin korunması için devletin, bu işlemleri anayasal ve kanuni düzenlemelere uygun olarak gerçekleştirmesini düzenler. devlet, devletleştirme ve özelleştirme işlemlerini adil ve hukuka uygun olarak gerçekleştirmek zorundadır.

CLEAN GENERATED:
Anasayfa maddesi 47, kamu hizmeti niteliği taşıyan özel teşebbüslerin devletleştirilmesi hakkında söylenmektedir. Devletleştirme gerçek karşılığı ile yapılır ve gerçek karşılığın hesaplanma tarzı ve usulleri, kanunla düzenlenir (Context 1). İkinci fıkra da, taksitlendirmelerde ve ödenmemiş kamulaştırma bedellerinde kamu alacakları için en yüksek faiz uygulanır
========================================================================================================================
INDEX: 15
QUESTION:
Kişisel veriler hangi mevzuata göre işlenir?

EXPECTED:
Kvk kanununda ve diğer kanunlarda öngörülen mevzuata göre işlenir.

CLEAN GENERATED:
Kişisel veriler, kanunla düzenlenir. (Context 1)
========================================================================================================================
INDEX: 16
QUESTION:
Anayasa madde 140'a göre, hakimlerin ve savcıların görev ve yetkileri nasıl düzenlenir?

EXPECTED:
Anayasa madde 140'a göre, hakimlerin ve savcıların görev ve yetkileri, çalışma usulleri, mesleğe kabul, atanma, nakil, geçici yetki verme, yükselme, aylık, ödenek ve diğer özlük işleri, meslek içi eğitim, görevden uzaklaştırılma, emeklilik ve disiplin işlerine ilişkin esaslar kanunla düzenlenir.

CLEAN GENERATED:
Anasayfa Madde 140'da, hakimler ve savcıların görevleri meslekten yürütülür. Hakimler, mahkemelerin bağımsızlığı ve hakimlik teminatı esaslarına göre görev ifa ederler. Kanunla düzenlenme bilgisi bu metnin içinde verilmemiştir. (In accordance with Article 140 of the Constitution, the duties and powers of judges and prosecutors are carried out from their profession. Judges ensure the independence and jurisdiction of the courts in accordance with the fundamental principles. However, the regulation
========================================================================================================================
INDEX: 17
QUESTION:
Ekonomik ve sosyal konsey hangi anayasa maddesi ile düzenlenmiştir

EXPECTED:
Ekonomik ve sosyal konsey, türkiye cumhuriyeti anayasası'nın 115. maddesi ile düzenlenmiştir. bu madde, konseyi ve görevlerini belirler.

CLEAN GENERATED:
Answer cannot be found in the given context.
========================================================================================================================
INDEX: 18
QUESTION:
Bilgi edinme hakkının ihlali durumunda ne yapılabilir

EXPECTED:
Bilgi edinme hakkının ihlali durumunda, bireyler bilgi edinme değerlendirme kurulu'na başvurarak ihlalin durdurulmasını ve talep ettikleri bilgilere erişim sağlanmasını isteyebilirler.

CLEAN GENERATED:
Bilgi edinme hakkının ihlali durumunda, Bilgi Edinme Değerlendirme Kurulu tarafından yapılacak itirazları inceleyip, kararlar verebilir. (Context 2)

Therefore, when the right to information is violated, the Bilgi Edinme Değerlendirme Kurulu (Information Evaluation Board) can review the objections and make decisions regarding the use of the right to information in this regard. (Context 2)

So, the answer is: When the right to information is violated, the Information Evaluation Board can review t
========================================================================================================================
INDEX: 19
QUESTION:
İdari yargı nedir?

EXPECTED:
Hukuki dinlenilme hakkı, tarafların yargılama sürecinde savunmalarını yapabilme ve delillerini sunabilme hakkıdır.

CLEAN GENERATED:
İdari yargı, yönetim ve işlemleri gerçekleştirme konusunda kurul, adlı ve idari hakimler ve savcılar tarafından yapılan yargıdır. Bu yargı, idari işlemin uygulanması halinde telafisi güç veya imkansız zararların doğması ve idari işlemin açıkça hukuka aykırı olması şartlarının olduğu durumda gerekçe gösterilerek yürütmenin durdurulmasına nitelik verilir. (Context 1 ve Context 3

In [48]:
base_test_results_df["is_valid_sample"] = True
base_test_results_df.loc[19, "is_valid_sample"] = False

manual_scores_base = [
    0.0,  # 0 yanlış
    0.0,  # 1 yanlış
    0.5,  # 2 kısmen
    0.0,  # 3 cevap bulunamadı
    0.5,  # 4 kısmen: kesin hüküm vermiyor, bilirkişi kısmı yok
    0.0,  # 5 cevap yok
    0.0,  # 6 yanlış
    0.0,  # 7 cevap bulunamadı
    0.0,  # 8 yanlış
    0.5,  # 9 kısmen
    0.0,  # 10 cevap yok
    0.0,  # 11 yanlış
    0.0,  # 12 yanlış
    1.0,  # 13 doğru
    0.5,  # 14 kısmen
    0.5,  # 15 kısmen
    0.5,  # 16 kısmen
    0.0,  # 17 cevap yok
    1.0,  # 18 doğru/kabul edilebilir
    0.0   # 19 invalid, skora katılmayacak
]

base_test_results_df["manual_score"] = manual_scores_base

valid_base_df = base_test_results_df[base_test_results_df["is_valid_sample"] == True]
base_test_score = valid_base_df["manual_score"].mean()

print("Base RAG Test Score:", base_test_score)
print("Valid sample count:", len(valid_base_df))

Base RAG Test Score: 0.2631578947368421
Valid sample count: 19

In [49]:
test_comparison_df = pd.DataFrame([
    {"method": "Base RAG", "manual_accuracy": base_test_score},
    {"method": "Strict Prompt RAG", "manual_accuracy": strict_test_score}
])

test_comparison_df

              method  manual_accuracy
0           Base RAG         0.263158
1  Strict Prompt RAG         0.263158