# Final System Colab Runner

This notebook runs the final custom RAG benchmark system in Google Colab.

It is intended for GPU-based testing of:

- retrieval-only mode
- base RAG mode
- fine-tuned RAG mode
- base vs fine-tuned comparison mode

The final runnable system is located under `final_system/` in the GitHub repository.

In [ ]:
import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("GPU not available. Please use Runtime > Change runtime type > L4 GPU.")

CUDA available: True
GPU: NVIDIA L4

In [ ]:
import os
import shutil
from pathlib import Path

REPO_URL = "https://github.com/Kutay11019/turkish-legal-rag.git"
REPO_DIR = Path("/content/turkish-legal-rag")

if REPO_DIR.exists():
    shutil.rmtree(REPO_DIR)

!git clone {REPO_URL} {REPO_DIR}

print("Repo cloned to:", REPO_DIR)
print("final_system exists:", (REPO_DIR / "final_system").exists())

Cloning into '/content/turkish-legal-rag'...
remote: Enumerating objects: 206, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (172/172), done.
remote: Total 206 (delta 98), reused 133 (delta 30), pack-reused 0 (from 0)
Receiving objects: 100% (206/206), 779.59 KiB | 8.38 MiB/s, done.
Resolving deltas: 100% (98/98), done.
Repo cloned to: /content/turkish-legal-rag
final_system exists: True

## Using the Sample Benchmark or Your Own Benchmark

This notebook can be executed with the included sample files. However, the provided `sample_legal_document.txt` and `sample_benchmark.csv` are only small smoke-test examples. They contain only two simple test questions, so the generated scores should not be interpreted as real project performance.

If you want to test the system with your own benchmark, you can use one of the following options:

1. Open `final_system/data/custom_benchmark/sample_benchmark.csv` and replace its content with your own benchmark questions.
2. Delete the existing `sample_benchmark.csv` file and upload your own benchmark file with the same name: `sample_benchmark.csv`.

Your benchmark CSV must contain at least these columns:

```csv
question,expected_answer
```

If you also want to use your own legal documents, place them under:

```text
final_system/data/custom_documents/
```

After adding or replacing the benchmark/document files, you do not need to restart the notebook from the beginning. Continue by running the next cell after the file upload/replacement step.

In [ ]:
FINAL_SYSTEM_DIR = REPO_DIR / "final_system"

%cd {FINAL_SYSTEM_DIR}

!python -m pip install --upgrade pip
!python -m pip install -r requirements.txt

# Needed for 4-bit GPU loading and Drive download
!python -m pip install -q bitsandbytes gdown

/content/turkish-legal-rag/final_system
Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Downloading pip-26.1.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.1.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 83.6 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed pip-26.1.1
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (4.67.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (6.0.3)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (5.5.1)
Collecting rank-bm25 (from -r requirements.txt (line 7))
  Downloading rank_bm25-0.2.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 9)) (1.13.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 10)) (0.19.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 11)) (2.11.0+cu128)
Collecting pymupdf (from -r requirements.txt (line 12))
  Downloading pymupdf-1.27.2.3-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (24 kB)
Collecting python-docx (from -r requirements.txt (line 13))
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 1)) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 6)) (1.16.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 6)) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (3.29.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (26.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (0.28.1)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (0.25.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (0.16.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate->-r requirements.txt (line 9)) (5.9.5)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (12.9.6)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 11)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r requirements.txt (line 11)) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch->-r requirements.txt (line 11)) (1.5.4)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx->-r requirements.txt (line 13)) (6.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->-r requirements.txt (line 11)) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (8.4.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers->-r requirements.txt (line 6)) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->-r requirements.txt (line 11)) (3.0.3)
Downloading rank_bm25-0.2.2-py3-none-any.whl (8.6 kB)
Downloading pymupdf-1.27.2.3-cp310-abi3-manylinux_2_28_x86_64.whl (25.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.0/25.0 MB 157.6 MB/s  0:00:00
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
Installing collected packages: rank-bm25, python-docx, pymupdf
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pymupdf]
Successfully installed pymupdf-1.27.2.3 python-docx-1.2.0 rank-bm25-0.2.2

In [ ]:
from pathlib import Path
import subprocess
import os

ADAPTER_DRIVE_FILE_LINK = "https://drive.google.com/file/d/1VyKe4-oydf8LUs_rmnu02079tFCZkIGO/view?usp=sharing"

DOWNLOAD_DIR = Path("/content/adapter_download")
DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

adapter_zip_path = DOWNLOAD_DIR / "mistral_legal_qlora_starlar_v2_800steps_clean.zip"

print("Downloading adapter zip from Google Drive...")
print("Output path:", adapter_zip_path)

result = subprocess.run(
    [
        "gdown",
        "--fuzzy",
        ADAPTER_DRIVE_FILE_LINK,
        "-O",
        str(adapter_zip_path)
    ],
    capture_output=True,
    text=True
)

print("STDOUT:")
print(result.stdout)

print("STDERR:")
print(result.stderr)

print("Zip exists:", adapter_zip_path.exists())

if not adapter_zip_path.exists():
    raise FileNotFoundError("Adapter zip was not downloaded. Check the direct file sharing link.")

print("Zip size MB:", round(adapter_zip_path.stat().st_size / (1024 * 1024), 2))

Downloading adapter zip from Google Drive...
Output path: /content/adapter_download/mistral_legal_qlora_starlar_v2_800steps_clean.zip
STDOUT:

STDERR:
Downloading...
From (original): https://drive.google.com/uc?id=1VyKe4-oydf8LUs_rmnu02079tFCZkIGO
From (redirected): https://drive.google.com/uc?id=1VyKe4-oydf8LUs_rmnu02079tFCZkIGO&confirm=t&uuid=b743f9d5-a8bf-4ce3-83bf-83530e713b7c
To: /content/adapter_download/mistral_legal_qlora_starlar_v2_800steps_clean.zip

  0%|          | 0.00/156M [00:00<?, ?B/s]
  4%|▍         | 6.82M/156M [00:00<00:02, 53.5MB/s]
  9%|▉         | 14.7M/156M [00:00<00:02, 64.7MB/s]
 15%|█▌        | 23.6M/156M [00:00<00:01, 68.0MB/s]
 23%|██▎       | 35.7M/156M [00:00<00:01, 85.8MB/s]
 31%|███▏      | 48.8M/156M [00:00<00:01, 94.6MB/s]
 41%|████      | 63.4M/156M [00:00<00:00, 110MB/s]
 48%|████▊     | 75.0M/156M [00:00<00:00, 95.0MB/s]
 54%|█████▍    | 84.9M/156M [00:00<00:00, 85.2MB/s]
 61%|██████    | 94.9M/156M [00:01<00:00, 88.5MB/s]
 68%|██████▊   | 105M/156M [00:01<00:00, 90.9MB/s]
 74%|███████▎  | 115M/156M [00:01<00:00, 87.6MB/s]
 81%|████████  | 126M/156M [00:01<00:00, 91.3MB/s]
 87%|████████▋ | 135M/156M [00:01<00:00, 89.4MB/s]
 94%|█████████▍| 146M/156M [00:01<00:00, 93.9MB/s]
100%|██████████| 156M/156M [00:01<00:00, 90.2MB/s]
100%|██████████| 156M/156M [00:01<00:00, 88.6MB/s]

Zip exists: True
Zip size MB: 148.65

In [ ]:
import zipfile
import shutil

ADAPTER_TARGET_DIR = FINAL_SYSTEM_DIR / "models" / "mistral_legal_qlora_starlar_v2_800steps"

if ADAPTER_TARGET_DIR.exists():
    shutil.rmtree(ADAPTER_TARGET_DIR)

ADAPTER_TARGET_DIR.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(adapter_zip_path, "r") as z:
    z.extractall(ADAPTER_TARGET_DIR)

print("Adapter extracted to:", ADAPTER_TARGET_DIR)

print("\nFiles:")
for item in sorted(ADAPTER_TARGET_DIR.iterdir()):
    print("-", item.name)

print("\nRequired file check:")
print("adapter_config.json:", (ADAPTER_TARGET_DIR / "adapter_config.json").exists())
print("adapter_model.safetensors:", (ADAPTER_TARGET_DIR / "adapter_model.safetensors").exists())

Adapter extracted to: /content/turkish-legal-rag/final_system/models/mistral_legal_qlora_starlar_v2_800steps

Files:
- README.md
- adapter_config.json
- adapter_model.safetensors
- chat_template.jinja
- tokenizer.json
- tokenizer_config.json
- training_args.bin

Required file check:
adapter_config.json: True
adapter_model.safetensors: True

In [ ]:
import yaml

CONFIG_PATH = FINAL_SYSTEM_DIR / "config.yaml"

with open(CONFIG_PATH, "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

config["models"]["local_finetuned_adapter"] = "models/mistral_legal_qlora_starlar_v2_800steps"

with open(CONFIG_PATH, "w", encoding="utf-8") as f:
    yaml.safe_dump(config, f, sort_keys=False, allow_unicode=True)

print("Updated config.yaml")
print("local_finetuned_adapter:", config["models"]["local_finetuned_adapter"])

Updated config.yaml
local_finetuned_adapter: models/mistral_legal_qlora_starlar_v2_800steps

In [ ]:
from huggingface_hub import login

login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
%cd {FINAL_SYSTEM_DIR}

!python run_custom_rag_benchmark.py --mode base --retrieval_only

/content/turkish-legal-rag/final_system
================================================================================
Turkish Legal RAG Final System
================================================================================
Documents directory: /content/turkish-legal-rag/final_system/data/custom_documents
Benchmark path: /content/turkish-legal-rag/final_system/data/custom_benchmark/sample_benchmark.csv
Output directory: /content/turkish-legal-rag/final_system/data/outputs
Mode: base
Retrieval only: True
================================================================================
Loaded documents: 1
Built chunks: 1
Benchmark rows: 2
modules.json: 100% 229/229 [00:00<00:00, 963kB/s]
config_sentence_transformers.json: 100% 122/122 [00:00<00:00, 604kB/s]
README.md: 100% 3.89k/3.89k [00:00<00:00, 2.26MB/s]
sentence_bert_config.json: 100% 53.0/53.0 [00:00<00:00, 287kB/s]
config.json: 100% 645/645 [00:00<00:00, 3.33MB/s]
model.safetensors: 100% 471M/471M [00:02<00:00, 216MB/s]
Loading weights: 100% 199/199 [00:00<00:00, 1252.22it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
tokenizer_config.json: 100% 526/526 [00:00<00:00, 2.60MB/s]
tokenizer.json: 100% 9.08M/9.08M [00:01<00:00, 9.00MB/s]
special_tokens_map.json: 100% 239/239 [00:00<00:00, 1.21MB/s]
config.json: 100% 190/190 [00:00<00:00, 761kB/s]
Batches: 100% 1/1 [00:00<00:00,  1.60it/s]
Running base: 100% 2/2 [00:00<00:00, 16.06it/s]
Saved base results to: /content/turkish-legal-rag/final_system/data/outputs/base_rag_results.csv
Saved summary to: /content/turkish-legal-rag/final_system/data/outputs/base_vs_finetuned_summary.csv

Final summary:
   mode  sample_count  ...  mean_text_similarity  source_citation_rate
0  base             2  ...                   0.0                   0.0

[1 rows x 5 columns]

In [ ]:
import pandas as pd

base_results_path = FINAL_SYSTEM_DIR / "data" / "outputs" / "base_rag_results.csv"
summary_path = FINAL_SYSTEM_DIR / "data" / "outputs" / "base_vs_finetuned_summary.csv"

base_results_df = pd.read_csv(base_results_path)
summary_df = pd.read_csv(summary_path)

display(summary_df)
display(base_results_df[["question", "expected_answer", "top1_file_name", "top1_context"]])

,mode,sample_count,mean_token_f1,mean_text_similarity,source_citation_rate
0,base,2,0.0,0.0,0.0

,question,expected_answer,top1_file_name,top1_context
0,Anayasa 10. madde neyi düzenler?,"Anayasa 10. madde, herkesin kanun önünde eşit ...",sample_legal_document.txt,Türkiye Cumhuriyeti Anayasası Madde 10 – Herke...
1,Bilgi edinme hakkı ihlal edilirse ne yapılabilir?,Bilgi edinme hakkının ihlali durumunda ilgili ...,sample_legal_document.txt,Türkiye Cumhuriyeti Anayasası Madde 10 – Herke...

In [ ]:
%cd {FINAL_SYSTEM_DIR}

!python run_custom_rag_benchmark.py --mode base

/content/turkish-legal-rag/final_system
================================================================================
Turkish Legal RAG Final System
================================================================================
Documents directory: /content/turkish-legal-rag/final_system/data/custom_documents
Benchmark path: /content/turkish-legal-rag/final_system/data/custom_benchmark/sample_benchmark.csv
Output directory: /content/turkish-legal-rag/final_system/data/outputs
Mode: base
Retrieval only: False
================================================================================
Loaded documents: 1
Built chunks: 1
Benchmark rows: 2
Loading weights: 100% 199/199 [00:00<00:00, 969.47it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100% 1/1 [00:00<00:00,  5.60it/s]
config.json: 100% 596/596 [00:00<00:00, 2.88MB/s]
tokenizer_config.json: 100% 2.10k/2.10k [00:00<00:00, 5.13MB/s]
tokenizer.json: 100% 1.80M/1.80M [00:00<00:00, 23.1MB/s]
tokenizer.model: 100% 493k/493k [00:01<00:00, 464kB/s]
special_tokens_map.json: 100% 414/414 [00:00<00:00, 797kB/s]
`torch_dtype` is deprecated! Use `dtype` instead!
model.safetensors.index.json: 100% 25.1k/25.1k [00:00<00:00, 32.6MB/s]
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Downloading (incomplete total...):  85% 12.4G/14.5G [00:38<00:06, 349MB/s]
Downloading (incomplete total...): 100% 14.5G/14.5G [00:40<00:00, 514MB/s]
Fetching 3 files: 100% 3/3 [00:40<00:00, 13.51s/it]
Download complete: 100% 14.5G/14.5G [00:40<00:00, 357MB/s]
Loading weights:   1% 4/291 [00:00<00:17, 16.75it/s, Materializing param=model.layers.0.mlp.down_proj.weight]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Loading weights: 100% 291/291 [00:04<00:00, 62.59it/s, Materializing param=model.norm.weight]
generation_config.json: 100% 111/111 [00:00<00:00, 539kB/s]
Running base:   0% 0/2 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Running base:  50% 1/2 [00:16<00:16, 16.44s/it]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Running base: 100% 2/2 [00:21<00:00, 10.95s/it]
Saved base results to: /content/turkish-legal-rag/final_system/data/outputs/base_rag_results.csv
Saved summary to: /content/turkish-legal-rag/final_system/data/outputs/base_vs_finetuned_summary.csv

Final summary:
   mode  sample_count  ...  mean_text_similarity  source_citation_rate
0  base             2  ...               0.35705                   0.0

[1 rows x 5 columns]

In [ ]:
base_results_df = pd.read_csv(FINAL_SYSTEM_DIR / "data" / "outputs" / "base_rag_results.csv")
summary_df = pd.read_csv(FINAL_SYSTEM_DIR / "data" / "outputs" / "base_vs_finetuned_summary.csv")

display(summary_df)
display(base_results_df[["question", "expected_answer", "generated_answer", "top1_context"]])

,mode,sample_count,mean_token_f1,mean_text_similarity,source_citation_rate
0,base,2,0.210764,0.35705,0.0

,question,expected_answer,generated_answer,top1_context
0,Anayasa 10. madde neyi düzenler?,"Anayasa 10. madde, herkesin kanun önünde eşit ...","Anayasa 10. madde, Türkiye Cumhuriyeti Anayasa...",Türkiye Cumhuriyeti Anayasası Madde 10 – Herke...
1,Bilgi edinme hakkı ihlal edilirse ne yapılabilir?,Bilgi edinme hakkının ihlali durumunda ilgili ...,Bilgi edinme hakkı ihlal edilmese değerlendiri...,Türkiye Cumhuriyeti Anayasası Madde 10 – Herke...

In [ ]:
%cd {FINAL_SYSTEM_DIR}

!python run_custom_rag_benchmark.py --mode finetuned

/content/turkish-legal-rag/final_system
================================================================================
Turkish Legal RAG Final System
================================================================================
Documents directory: /content/turkish-legal-rag/final_system/data/custom_documents
Benchmark path: /content/turkish-legal-rag/final_system/data/custom_benchmark/sample_benchmark.csv
Output directory: /content/turkish-legal-rag/final_system/data/outputs
Mode: finetuned
Retrieval only: False
================================================================================
Loaded documents: 1
Built chunks: 1
Benchmark rows: 2
Loading weights: 100% 199/199 [00:00<00:00, 1101.20it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100% 1/1 [00:00<00:00,  5.51it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights:   1% 4/291 [00:00<00:24, 11.50it/s, Materializing param=model.layers.0.mlp.down_proj.weight]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Loading weights: 100% 291/291 [00:04<00:00, 62.79it/s, Materializing param=model.norm.weight]
Running finetuned:   0% 0/2 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Running finetuned:  50% 1/2 [00:30<00:30, 30.43s/it]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Running finetuned: 100% 2/2 [01:00<00:00, 30.20s/it]
Saved finetuned results to: /content/turkish-legal-rag/final_system/data/outputs/finetuned_rag_results.csv
Saved summary to: /content/turkish-legal-rag/final_system/data/outputs/base_vs_finetuned_summary.csv

Final summary:
        mode  sample_count  ...  mean_text_similarity  source_citation_rate
0  finetuned             2  ...              0.194487                   0.5

[1 rows x 5 columns]

In [ ]:
finetuned_results_df = pd.read_csv(FINAL_SYSTEM_DIR / "data" / "outputs" / "finetuned_rag_results.csv")
summary_df = pd.read_csv(FINAL_SYSTEM_DIR / "data" / "outputs" / "base_vs_finetuned_summary.csv")

display(summary_df)
display(finetuned_results_df[["question", "expected_answer", "generated_answer", "top1_context"]])

,mode,sample_count,mean_token_f1,mean_text_similarity,source_citation_rate
0,finetuned,2,0.102728,0.194487,0.5

,question,expected_answer,generated_answer,top1_context
0,Anayasa 10. madde neyi düzenler?,"Anayasa 10. madde, herkesin kanun önünde eşit ...",Anayasa 10. madde şu düzenler yapar: Türkiye C...,Türkiye Cumhuriyeti Anayasası Madde 10 – Herke...
1,Bilgi edinme hakkı ihlal edilirse ne yapılabilir?,Bilgi edinme hakkının ihlali durumunda ilgili ...,Bu açıklama şu kaynak bilgilerine dayandırılma...,Türkiye Cumhuriyeti Anayasası Madde 10 – Herke...

In [ ]:
%cd {FINAL_SYSTEM_DIR}

!python run_custom_rag_benchmark.py --mode both

/content/turkish-legal-rag/final_system
================================================================================
Turkish Legal RAG Final System
================================================================================
Documents directory: /content/turkish-legal-rag/final_system/data/custom_documents
Benchmark path: /content/turkish-legal-rag/final_system/data/custom_benchmark/sample_benchmark.csv
Output directory: /content/turkish-legal-rag/final_system/data/outputs
Mode: both
Retrieval only: False
================================================================================
Loaded documents: 1
Built chunks: 1
Benchmark rows: 2
Loading weights: 100% 199/199 [00:00<00:00, 1053.33it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100% 1/1 [00:00<00:00,  5.53it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights:   1% 4/291 [00:00<00:17, 16.39it/s, Materializing param=model.layers.0.mlp.down_proj.weight]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Loading weights: 100% 291/291 [00:04<00:00, 64.30it/s, Materializing param=model.norm.weight]
Running base:   0% 0/2 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Running base:  50% 1/2 [00:17<00:17, 17.20s/it]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Running base: 100% 2/2 [00:22<00:00, 11.50s/it]
Saved base results to: /content/turkish-legal-rag/final_system/data/outputs/base_rag_results.csv
Loading weights:   1% 4/291 [00:00<00:31,  9.01it/s, Materializing param=model.layers.0.mlp.down_proj.weight]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Loading weights: 100% 291/291 [00:04<00:00, 63.48it/s, Materializing param=model.norm.weight]
Running finetuned:   0% 0/2 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Running finetuned:  50% 1/2 [00:30<00:30, 30.97s/it]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Running finetuned: 100% 2/2 [01:01<00:00, 30.73s/it]
Saved finetuned results to: /content/turkish-legal-rag/final_system/data/outputs/finetuned_rag_results.csv
Saved summary to: /content/turkish-legal-rag/final_system/data/outputs/base_vs_finetuned_summary.csv

Final summary:
        mode  sample_count  ...  mean_text_similarity  source_citation_rate
0       base             2  ...              0.357050                   0.0
1  finetuned             2  ...              0.194487                   0.5

[2 rows x 5 columns]

In [ ]:
base_results_df = pd.read_csv(FINAL_SYSTEM_DIR / "data" / "outputs" / "base_rag_results.csv")
finetuned_results_df = pd.read_csv(FINAL_SYSTEM_DIR / "data" / "outputs" / "finetuned_rag_results.csv")
summary_df = pd.read_csv(FINAL_SYSTEM_DIR / "data" / "outputs" / "base_vs_finetuned_summary.csv")

display(summary_df)

comparison_df = pd.DataFrame({
    "question": base_results_df["question"],
    "expected_answer": base_results_df["expected_answer"],
    "base_answer": base_results_df["generated_answer"],
    "finetuned_answer": finetuned_results_df["generated_answer"],
    "base_token_f1": base_results_df["token_f1"],
    "finetuned_token_f1": finetuned_results_df["token_f1"],
    "base_similarity": base_results_df["text_similarity"],
    "finetuned_similarity": finetuned_results_df["text_similarity"],
})

display(comparison_df)

,mode,sample_count,mean_token_f1,mean_text_similarity,source_citation_rate
0,base,2,0.210764,0.357050,0.0
1,finetuned,2,0.102728,0.194487,0.5

,question,expected_answer,base_answer,finetuned_answer,base_token_f1,finetuned_token_f1,base_similarity,finetuned_similarity
0,Anayasa 10. madde neyi düzenler?,"Anayasa 10. madde, herkesin kanun önünde eşit ...","Anayasa 10. madde, Türkiye Cumhuriyeti Anayasa...",Anayasa 10. madde şu düzenler yapar: Türkiye C...,0.179104,0.176471,0.226496,0.217659
1,Bilgi edinme hakkı ihlal edilirse ne yapılabilir?,Bilgi edinme hakkının ihlali durumunda ilgili ...,Bilgi edinme hakkı ihlal edilmese değerlendiri...,Bu açıklama şu kaynak bilgilerine dayandırılma...,0.242424,0.028986,0.487603,0.171315

In [ ]:
from pathlib import Path

output_files = [
    FINAL_SYSTEM_DIR / "data" / "outputs" / "base_rag_results.csv",
    FINAL_SYSTEM_DIR / "data" / "outputs" / "finetuned_rag_results.csv",
    FINAL_SYSTEM_DIR / "data" / "outputs" / "base_vs_finetuned_summary.csv",
]

print("FINAL OUTPUT FILE CHECK")
print("=" * 80)

for path in output_files:
    print(path)
    print("Exists:", path.exists())
    if path.exists():
        print("Size KB:", round(path.stat().st_size / 1024, 2))
    print("-" * 80)

FINAL OUTPUT FILE CHECK
================================================================================
/content/turkish-legal-rag/final_system/data/outputs/base_rag_results.csv
Exists: True
Size KB: 3.32
--------------------------------------------------------------------------------
/content/turkish-legal-rag/final_system/data/outputs/finetuned_rag_results.csv
Exists: True
Size KB: 3.64
--------------------------------------------------------------------------------
/content/turkish-legal-rag/final_system/data/outputs/base_vs_finetuned_summary.csv
Exists: True
Size KB: 0.18
--------------------------------------------------------------------------------

In [ ]:
import pandas as pd

base_df = pd.read_csv("/content/turkish-legal-rag/final_system/data/outputs/base_rag_results.csv")
ft_df = pd.read_csv("/content/turkish-legal-rag/final_system/data/outputs/finetuned_rag_results.csv")

comparison_df = pd.DataFrame({
    "question": base_df["question"],
    "expected_answer": base_df["expected_answer"],
    "base_answer": base_df["generated_answer"],
    "finetuned_answer": ft_df["generated_answer"],
    "base_token_f1": base_df["token_f1"],
    "finetuned_token_f1": ft_df["token_f1"],
    "base_similarity": base_df["text_similarity"],
    "finetuned_similarity": ft_df["text_similarity"],
})

display(comparison_df)

,question,expected_answer,base_answer,finetuned_answer,base_token_f1,finetuned_token_f1,base_similarity,finetuned_similarity
0,Anayasa 10. madde neyi düzenler?,"Anayasa 10. madde, herkesin kanun önünde eşit ...","Anayasa 10. madde, Türkiye Cumhuriyeti Anayasa...",Anayasa 10. madde şu düzenler yapar: Türkiye C...,0.179104,0.176471,0.226496,0.217659
1,Bilgi edinme hakkı ihlal edilirse ne yapılabilir?,Bilgi edinme hakkının ihlali durumunda ilgili ...,Bilgi edinme hakkı ihlal edilmese değerlendiri...,Bu açıklama şu kaynak bilgilerine dayandırılma...,0.242424,0.028986,0.487603,0.171315